<?php

$organisations_0 = [
	[
		'id' => "organisation_wo_ugb",
		'name' => "United Groups for the Balance",
		'name_fr' => "Groupes Unis pour l'Équilibre",
		'acronym' => "UGB",
		'danger_level' => 0,
		'security_index' => 5,
		'part_of_ugb' => true,
		'countries' => ['WO'],
		'description' => "Il s'agit de l'organisation principale fondée par l'Ordre, peu après sa création. Elle rassemble tous les groupes humains reconnaissant les Tomes de l'Équilibre et s'assurant de leur respect sur leur territoire. Certains sont un département secret du gouvernement, d'autres sont des initiatives indépendantes liées à un pays, d'autres encore vont au-delà des frontières étatiques. La majorité d'entre elles sont en capacité d'arrêter et de juger selon la loi, ainsi que de participer aux discussions de modification des Tomes de l'Équilibre. Quelques autres groupes sont plus limités dans leurs droits, généralement à cause de leur influence moins grande ou de leurs actions plus spécifiques à un type de créatures cachées. Ces membres observateurs apportent tout de même une aide non négligeable et font pleinement partie de l'effort de collaboration pour assurer l'Équilibre du Plan Terrestre.",
		'created_at' => NULL,'updated_at' => NULL
	],
	[
		'id' => "organisation_wo_hpsa",
		'name' => "Human Policy Security Agency",
		'name_fr' => "Agence de Sécurité de la Politique Humaine",
		'acronym' => "HPSA",
		'danger_level' => 0,
		'security_index' => 5,
		'part_of_ugb' => true,
		'countries' => ['WO'],
		'description' => "Ses membres assurent que le surnaturel ne soit pas utilisé pour influencer la politique humaine du Plan Terrestre. Ils sont infiltrés dans différents corps gouvernementaux et militaires à travers le monde et ont accès à des mesures d'urgence pour contrôler les corruptions surnaturelles repérées.",
		'created_at' => NULL,'updated_at' => NULL
	],
	[
		'id' => "organisation_wo_cosmoss",
		'name' => "Committee for the Study, Masking and Oversight of the Supernatural in Space",
		'name_fr' => "Comité d'Étude, de Masquage et de Surveillance du Surnaturel dans l'Espace",
		'acronym' => "CoSMOSS",
		'danger_level' => 0,
		'security_index' => 5,
		'part_of_ugb' => true,
		'countries' => ['WO'],
		'description' => "Regroupement de scientifiques travaillant dans différentes agences de recherche spatiale. Ils ont pour objectif d’étudier le surnaturel dans l’espace, de prévenir sa découverte par le reste de l’humanité, et de surveiller ses possibles dangers.",
		'created_at' => NULL,'updated_at' => NULL
	],
	[
		'id' => "organisation_ca_chwis",
		'name' => "Canadian Hidden World Investigation Services",
		'name_fr' => "Services Canadiens d'Enquête du Monde Caché",
		'acronym' => "CHWIS",
		'danger_level' => 0,
		'security_index' => 42,
		'part_of_ugb' => true,
		'countries' => ['CA'],
		'description' => "Organisation gouvernementale.",
		'created_at' => NULL,'updated_at' => NULL
	],
	[
		'id' => "organisation_us_wemad",
		'name' => "Weird and Magical Affairs Department",
		'name_fr' => "Département des Affaires Étranges et Magiques",
		'acronym' => "WeMAD",
		'danger_level' => 0,
		'security_index' => 41,
		'part_of_ugb' => true,
		'countries' => ['US'],
		'description' => "Organisation gouvernementale.",
		'created_at' => NULL,'updated_at' => NULL
	],
	[
		'id' => "organisation_mx_dgsso",
		'name' => "Dirección General de Servicios de Seguridad Oculta",
		'name_fr' => "Direction Générale des Services de Sécurité Occulte",
		'acronym' => "DGSSO",
		'danger_level' => 0,
		'security_index' => 31,
		'part_of_ugb' => true,
		'countries' => ['MX'],
		'description' => "Branche de la Police ministérielle fédérale du Mexique.",
		'created_at' => NULL,'updated_at' => NULL
	],
	[
		'id' => "organisation_cr_m2s",
		'name' => "Movimiento Social Sobrenatural",
		'name_fr' => "Mouvement Social Surnaturel",
		'acronym' => "M2S",
		'danger_level' => 0,
		'security_index' => 38,
		'part_of_ugb' => true,
		'countries' => ['CR'],
		'description' => "Association démocratique visant à faire respecter les Tomes de l'Équilibre. Depuis la suppression de l'armée du Costa Rica en 1948, les membres de la M2S ne possèdent plus aucun droit à user de violence. La protection du territoire costaricien est prise en charge par le <a class='orga_danger_0' data-orga-ref='organisation_us_wemad'>WeMAD</a> des Etats-Unis.",
		'created_at' => NULL,'updated_at' => NULL
	],
	[
		'id' => "organisation_ni_gon",
		'name' => "Guardia de Orden de Nicaragua",
		'name_fr' => "Garde de l'Ordre du Niacaragua",
		'acronym' => "GON",
		'danger_level' => 0,
		'security_index' => 19,
		'part_of_ugb' => true,
		'countries' => ['NI'],
		'description' => "Milice nationale du pays représentant l'Ordre et faisant appliquer les Tomes de l'Équilibre sur le territoire.",
		'created_at' => NULL,'updated_at' => NULL
	],
	[
		'id' => "organisation_pa_fhemo",
		'name' => "Fuerzas Humanas para el Equilibrio del Mundo Oculto",
		'name_fr' => "Forces Humaines pour l'Équilibre du Monde Caché",
		'acronym' => "FHEMO",
		'danger_level' => 0,
		'security_index' => 25,
		'part_of_ugb' => true,
		'countries' => ['PA'],
		'description' => "Originellement rattaché au gouvernement, l'agence a dû se restructurer lorsque la Force de défense panaméenne a été démantelée après l'invasion américaine de 1989. Elle est aujourd'hui un groupe indépendant. L'accord avec les Etats-Unis autorise le <a class='orga_danger_0' data-orga-ref='organisation_us_wemad'>WeMAD</a> à intervenir unilatéralement si la neutralité ou la sécurité du canal de Panama sont en danger pour des raisons surnaturelles.",
		'created_at' => NULL,'updated_at' => NULL
	],
	[
		'id' => "organisation_ht_bao",
		'name' => "Bureau des Affaires Occultes",
		'name_fr' => "Bureau des Affaires Occultes",
		'acronym' => "BAO",
		'danger_level' => 44,
		'security_index' => 35,
		'part_of_ugb' => true,
		'countries' => ['HT'],
		'description' => "Unité spéciale de la Police Nationale d'Haïti.",
		'created_at' => NULL,'updated_at' => NULL
	],
	[
		'id' => "organisation_jm_dmc",
		'name' => "Department of Magic Control",
		'name_fr' => "Département de Contrôle de la Magie",
		'acronym' => "DMC",
		'danger_level' => 0,
		'security_index' => 42,
		'part_of_ugb' => true,
		'countries' => ['JM'],
		'description' => "Division du Ministère de la Sécurité Nationale de la Jamaïque.",
		'created_at' => NULL,'updated_at' => NULL
	],
	[
		'id' => "organisation_do_dgms",
		'name' => "Departamento de Gestión del Mundo Secreto",
		'name_fr' => "Département de Gestion du Monde Secret",
		'acronym' => "DGMS",
		'danger_level' => 0,
		'security_index' => 43,
		'part_of_ugb' => true,
		'countries' => ['DO'],
		'description' => "Organisation gouvernementale.",
		'created_at' => NULL,'updated_at' => NULL
	],
	[
		'id' => "organisation_antilles_absu",
		'name' => "Antillean Association of Balance Security Units",
		'name_fr' => "Association Antillaise des Unités de Sécurité de l'Équilibre",
		'acronym' => "ABSU",
		'danger_level' => 0,
		'security_index' => 38,
		'part_of_ugb' => true,
		'countries' => ['BS', 'TC', 'KY', 'AG', 'BB', 'DM', 'GD', 'KN', 'LC', 'VC', 'TT', 'AW', 'AI', 'VG', 'CW', 'GP', 'MQ', 'MS', 'MF', 'VI'],
		'description' => "Entente entre les territoires insulaires des Caraïbes pour mettre en commun leurs ressources dans l'application des Tomes de l'Équilibre, se détachant ainsi des autorités des pays tutélaires pour gérer le surnaturel, souvent très spécifique à la région.",
		'created_at' => NULL,'updated_at' => NULL
	],
	[
		'id' => "organisation_caribbean_alma",
		'name' => "Alianza Mágico para los Pueblos de Nuestra América",
		'name_fr' => "Alliance magique pour les peuples de notre Amérique",
		'acronym' => "ALMA",
		'danger_level' => 0,
		'security_index' => 12,
		'part_of_ugb' => true,
		'countries' => ['CU', 'VE', 'BO', 'NI', 'DM', 'AG', 'VC', 'LC', 'KN', 'GD'],
		'description' => "signifiant Âme en espagnol. Entente secrète entre les membres de l'ALBA (Alliance bolivarienne pour les peuples de notre Amérique) créée en 2004 pour favoriser la logique coopérative entre les organismes liés au surnaturel de chaque pays, plutôt que laisser la porte ouverte à l'ingérence des Etats-Unis (et donc du WeMAD) sur leurs territoires.",
		'created_at' => NULL,'updated_at' => NULL
	],
	[
		'id' => "organisation_cl_civs",
		'name' => "Células Independientes de Vigilancia de lo Sobrenatural",
		'name_fr' => "Cellules Indépendantes pour la Surveillance du Surnaturel",
		'acronym' => "CIVS",
		'danger_level' => 0,
		'security_index' => 37,
		'part_of_ugb' => true,
		'countries' => ['CL'],
		'description' => "Organisation privée, fondée en 1975 après le coup d'état de Pinochet de 1973 par d'anciens membres du <a class='orga_danger_2' data-orga-ref='organisation_cl_dods'>DODS</a>. Ils suivent une organisation matricielle en cellules regroupant des agents aux compétences similaires pour répondre efficacement à des problématiques. La majorité des Chasseurs sont mobiles sur le pays, sans être affectés à un bureau spécifique (qui servent principalement à gérer l'administratif).",
		'created_at' => NULL,'updated_at' => NULL
	],
	[
		'id' => "organisation_co_pno",
		'name' => "Policía Nacional Ocultista",
		'name_fr' => "Police Nationale de l'Occulte",
		'acronym' => "PNO",
		'danger_level' => 0,
		'security_index' => 33,
		'part_of_ugb' => true,
		'countries' => ['CO'],
		'description' => "Force officielle dissoute durant la Violencia (1948-1960) par manque de ressources du gouvernement pour gérer le conflit civil. En 1968, l'Ordre aide financièrement la Colombie pour reformer la PNO. Mais le gouvernement colombien utilise ces fonds dans la lutte contre les guérillas. L'Ordre exerce donc une tutelle du pays pendant plusieurs années pendant le conflit armé colombien, mobilisant sur place ses propres agents pour pallier la non-gestion du pays. L'aide financière est de nouveau apportée en 2004 après que le gouvernement colombien ait signé un accord avec le groupe paramilitaire AUC, fusion de plusieurs groupes initialement fondés pour aider dans la lutte contre les guérillas mais devenus depuis criminel. La PNO est reconstituée, mais reste faible par rapport à la <a class='orga_danger_2' data-orga-ref='organisation_co_sr'>La Sombra Roja</a>.",
		'created_at' => NULL,'updated_at' => NULL
	],
	[
		'id' => "organisation_ec_iesm",
		'name' => "Instituto Ecuatoriano de Seguridad Mágica",
		'name_fr' => "Institut Equatorien de Sécurité Magique",
		'acronym' => "IESM",
		'danger_level' => 0,
		'security_index' => 37,
		'part_of_ugb' => true,
		'countries' => ['EC'],
		'description' => "Organisation gouvernementale.",
		'created_at' => NULL,'updated_at' => NULL
	],
	[
		'id' => "organisation_gy_bps",
		'name' => "Balance Preservation Service",
		'name_fr' => "Service de Préservation de l'Équilibre",
		'acronym' => "BPS",
		'danger_level' => 0,
		'security_index' => 39,
		'part_of_ugb' => true,
		'countries' => ['GY'],
		'description' => "Organisation gouvernementale.",
		'created_at' => NULL,'updated_at' => NULL
	],
	[
		'id' => "organisation_pe_sdp",
		'name' => "Sangre del Peru",
		'name_fr' => "Le Sang du Pérou",
		'acronym' => "",
		'danger_level' => 0,
		'security_index' => 40,
		'part_of_ugb' => true,
		'countries' => ['PE'],
		'description' => "Entente entre trois organisations - <span class='orga_danger_0'>Mandros de la Selva</span> (<span class='font-italic'>Méandres de la Selva</span>), <span class='orga_danger_0'>Nieves de la Sierra</span> (<span class='font-italic'>Neiges de la Sierra</span>), <span class='orga_danger_0'>Espuma de la </span> (<span class='font-italic'>Ecume de la Costa</span>) - gérant respectivement la jungle (Selva) au Nord-Est des montagnes, les montagnes (Sierra) et la partie côtière (Costa) au Sud-Ouest des Andes. Originellement, le gouvernement du Pérou s'occupait du surnaturel, mais, à plusieurs reprises l'a utilisé, dans ses nombreux conflits limitrophes. Lors de la lutte civile contre les terroristes d'extrême gauche du Sentier Lumineux, débutée en 1980, le gouvernement péruvien n'a plus hésité à utiliser le surnaturel au sein même de son pays, enclenchant une utilisation réciproque chez les terroristes (ainsi que le groupe plus petit du Mouvement Révolutionnaire Túpac Amaru). L'Ordre a créé trois divisions envoyées sur place : une pour démanteler le surnaturel au sein du gouvernement, une deuxième pour le démanteler au sein des rebelles, et une troisième pour assurer la sécurité des civils. Une fois le conflit calmé après plusieurs années, les trois divisions sont restées sur place, se séparant le territoire selon les trois zones géographiques.",
		'created_at' => NULL,'updated_at' => NULL
	],
	[
		'id' => "organisation_sr_bo",
		'name' => "Bovennatuurlijk Onderzoeksbureau",
		'name_fr' => "Bureau d'Enquête Surnaturelle",
		'acronym' => "BO",
		'danger_level' => 0,
		'security_index' => 45,
		'part_of_ugb' => true,
		'countries' => ['SR'],
		'description' => "Organisation gouvernementale.",
		'created_at' => NULL,'updated_at' => NULL
	],
	[
		'id' => "organisation_ve_sn",
		'name' => "Los Soldados del Oro Negro",
		'name_fr' => "Les Soldats de l'Or Noir",
		'acronym' => "",
		'danger_level' => 0,
		'security_index' => 19,
		'part_of_ugb' => true,
		'countries' => ['VE'],
		'description' => "Organisation qui cherchait originellement à empêcher les créatures surnaturelles de prendre la main sur l'économie pétrolière et de gaz du pays (25% du PIB et 95% des exportations). Elle a par la suite diversifié ses objectifs pour devenir un membre complet des <a class='orga_danger_0' data-orga-ref='organisation_wo_ugb'>UGB</a> (Groupes Unis pour l'Équilibre). Aujourd'hui, avec la crise économique du Venezuela dûe à la chute des cours du pétrole de 2013, les Soldados del Oro Negro sont suspectés de passer des accords avec certaines créatures surnaturelles pour tenter de redresser l'économie de leur pays.",
		'created_at' => NULL,'updated_at' => NULL
	],
	[
		'id' => "organisation_amazonia_be",
		'name' => "Buscadores de lo Extraño",
		'name_fr' => "Chercheurs de l'Étrange",
		'acronym' => "",
		'danger_level' => 0,
		'security_index' => 15,
		'part_of_ugb' => true,
		'countries' => ['BR', 'CO', 'EC', 'PE', 'VE'],
		'description' => "Envoyés par l'Ordre en collaboration avec la couronne espagnole lors de la découverte de l'Amérique pour s'occuper au plus vite du surnaturel lors des explorations, les Buscadores avaient pour responsabilité de trouver, de référencer et de garder secret le Monde Caché. Aujourd'hui, leur nombre a grandement diminué avec la mise en place d'organismes plus modernes et nationaux dans chaque pays. Mais ils restent actifs avec la même mission : débusquer le surnaturel et avertir les autorités compétentes, notamment dans les milieux très sauvages comme la forêt amazonienne.",
		'created_at' => NULL,'updated_at' => NULL
	],
	[
		'id' => "organisation_andes_ea",
		'name' => "Estrellas Andinas",
		'name_fr' => "Etoiles Andines",
		'acronym' => "",
		'danger_level' => 0,
		'security_index' => 22,
		'part_of_ugb' => true,
		'countries' => ['AR', 'CL', 'EC', 'PE'],
		'description' => "Réseau d'individus dispersés à travers les communautés isolées des montagnes. Ils surveillent les activités surnaturelles hors des radars des autres organisations et s'aventurent régulièrement loin des sentiers battus pour y réaliser leur surveillance. Ils peuvent également accompagner les renégats présents dans les villages andins, trop loin des grandes villes pour rejoindre un groupe et être correctement accompagnés au début de leur vie surnaturelle.",
		'created_at' => NULL,'updated_at' => NULL
	],
	[
		'id' => "organisation_de_bio",
		'name' => "Bundesministerium des Innern und für Ordnung",
		'name_fr' => "Ministère Fédéral de l'Intérieur et de l'Ordre",
		'acronym' => "BIO",
		'danger_level' => 0,
		'security_index' => 44,
		'part_of_ugb' => true,
		'countries' => ['DE'],
		'description' => "Organisation gouvernementale.",
		'created_at' => NULL,'updated_at' => NULL
	],
	[
		'id' => "organisation_fr_dgso",
		'name' => "Direction Générale de la Sécurité de l'Ordre",
		'name_fr' => "Direction Générale de la Sécurité de l'Ordre",
		'acronym' => "DGSO",
		'danger_level' => 0,
		'security_index' => 38,
		'part_of_ugb' => true,
		'countries' => ['FR', 'GF'],
		'description' => "Organisation gouvernementale.",
		'created_at' => NULL,'updated_at' => NULL
	],
	[
		'id' => "organisation_gb_mi12",
		'name' => "Balance Protection Office",
		'name_fr' => "Bureau de Protection de l'Équilibre",
		'acronym' => "MI12",
		'danger_level' => 0,
		'security_index' => 41,
		'part_of_ugb' => true,
		'countries' => ['GB'],
		'description' => "Agence gouvernementale de renseignements britanniques. Il s'agit en quelque sorte de l'équivalent du MI5 pour le surnaturel.",
		'created_at' => NULL,'updated_at' => NULL
	],
	[
		'id' => "organisation_in_mia",
		'name' => "Magical Intelligence Agency",
		'name_fr' => "Agence de Renseignement Magique",
		'acronym' => "MIA",
		'danger_level' => 0,
		'security_index' => 43,
		'part_of_ugb' => true,
		'countries' => ['IN'],
		'description' => "Organisation gouvernementale.",
		'created_at' => NULL,'updated_at' => NULL
	]
];

$organisations_1 = [
	[
		'id' => "organisation_mx_dn",
		'name' => "La Dalia Negra",
		'name_fr' => "Le Dahlia Noir",
		'acronym' => "",
		'danger_level' => 1,
		'security_index' => 04,
		'part_of_ugb' => false,
		'countries' => ['MX'],
		'description' => "Réseau d'entraide entre créatures du surnaturel, capable d'agir rapidement dans la plupart des situations sur le territoire mexicain. Le Dalia Negra a été créé afin de pallier l'absence de la DGSSO dans certains endroits, de proposer une alternative face au manque de confiance des créatures du Monde Caché envers la <a class='orga_danger_0' data-orga-ref='organisation_mx_dgsso'>DGSSO</a>, et d'accompagner les créatures cachées face aux violences les mettant en péril (kidnapping, drogues, etc.). Plusieurs membres de la Dalia Negra sont criminels mais leurs actions individuelles ne reflètent pas l'organisation qui n'est donc pas condamnée dans son ensemble.",
		'created_at' => NULL,'updated_at' => NULL
	],
	[
		'id' => "organisation_bz_hf",
		'name' => "Hidden Flowers",
		'name_fr' => "Les Fleurs Cachées",
		'acronym' => "",
		'danger_level' => 1,
		'security_index' => 34,
		'part_of_ugb' => false,
		'countries' => ['BZ'],
		'description' => "Organisation indépendante paramilitaire assurant la sécurité du surnaturel sur le territoire bélizien. Ils luttent principalement contre les <a class='orga_danger_2' data-orga-ref='organisation_sv_gt_hn_pm'>Morados</a> (voir ci-dessous) à la frontière avec le Guatemala, et maintiennent la paix et la liberté à l'intérieur du territoire. Les créatures surnaturelles sont acceptées parmi leurs membres, empêchant une reconnaissance officielle de l'Ordre. Leur collaboration a cependant toujours été positive. Ils sont aidés financièrement par le <a class='orga_danger_0' data-orga-ref='organisation_gb_mi12'>MI12</a> (Europe &gt; Royaume-Uni).",
		'created_at' => NULL,'updated_at' => NULL
	],
	[
		'id' => "organisation_cu_bdmo",
		'name' => "Brigadas de Defensa del Mundo Oculto",
		'name_fr' => "Brigades de Défense du Monde Caché",
		'acronym' => "BDMO",
		'danger_level' => 1,
		'security_index' => 48,
		'part_of_ugb' => false,
		'countries' => ['CU'],
		'description' => "Division intégrée à la Police Nationale Révolutionnaire du ministère cubain de l'Intérieur. La BDMO faisait autrefois partie des <a class='orga_danger_0' data-orga-ref='organisation_wo_ugb'>UGB</a> (Groupes Unis pour l'Équilibre) mais elle les a quittés durant la Guerre Froide. L'entièreté du territoire est recouverte par une protection et un contrôle des portails, empêchant quiconque d'y entrer par magie sans être détecté. Aujourd'hui, les relations avec la BDMO sont souvent lentes et délicates, mais elles restent cordiales.",
		'created_at' => NULL,'updated_at' => NULL
	],
	[
		'id' => "organisation_antilles_pmw",
		'name' => "Piti Mami Wata",
		'name_fr' => "Les Enfants de Mami Wata",
		'acronym' => "",
		'danger_level' => 1,
		'security_index' => 14,
		'part_of_ugb' => false,
		'countries' => ['BS', 'TC', 'KY', 'AG', 'BB', 'DM', 'GD', 'KN', 'LC', 'VC', 'TT', 'AW', 'AI', 'VG', 'CW', 'GP', 'MQ', 'MS', 'MF', 'VI'],
		'description' => "Organisation regroupant des membres de plusieurs pays des îles antillaises qui agissent sur toute la mer des Caraïbes (hors grandes îles) pour assurer la protection et le secret du surnaturel. Très proches des esprits, ils se revendiquent de la culture vaudou.",
		'created_at' => NULL,'updated_at' => NULL
	],
	[
		'id' => "organisation_pe_w",
		'name' => "Wasichiqku",
		'name_fr' => "Les Architectes",
		'acronym' => "",
		'danger_level' => 1,
		'security_index' => 0,
		'part_of_ugb' => false,
		'countries' => ['PE'],
		'description' => "Groupe constitué principalement de magiciens et de sorciers qui recréent les architectures des civilisations précolombiennes dans de nouveaux plans. Ils les peuplent ensuite de créatures surnaturelles qui commercent et s'organisent entre elles. Les Wasichiqku revendiquent l'objectif de proposer une vie alternative à celle sur le Plan Terrestre, mais ils sont suspectés d'y envoyer de force certaines créatures, d'y abriter des criminels ainsi que d'y réaliser des sacrifices humains.",
		'created_at' => NULL,'updated_at' => NULL
	],
	[
		'id' => "organisation_gb_oc",
		'name' => "Orchard of Consciousness",
		'name_fr' => "Le Verger de la Conscience",
		'acronym' => "",
		'danger_level' => 1,
		'security_index' => 04,
		'part_of_ugb' => false,
		'countries' => ['GB'],
		'description' => "Société amicale réunissant des membres dans le but de s'entraider et de se protéger. L'acceptation des membres n'est limitée par aucune condition surnaturelle,  et requiert seulement qu'un éventuel membre reconnaisse la conscience comme principe d'égalité, plutôt que l'humanité. Leur organisation est similaire à celle des loges maçonniques. Leur devise est \"Entraide dans l'Obscurité\". Basés aux Royaumes-Unis, leur influence s'étend dans quelques autres pays d'Europe Occidentale.",
		'created_at' => NULL,'updated_at' => NULL
	],
	[
		'id' => "organisation_jp_cij",
		'name' => "Clans Indépendants du Japon",
		'name_fr' => "Clans Indépendants du Japon",
		'acronym' => "",
		'danger_level' => 1,
		'security_index' => 40,
		'part_of_ugb' => false,
		'countries' => ['JP'],
		'description' => "Clans variés et indépendants chargés de protéger leurs zones. Les Tomes de l'Equilibre n'y sont pas reconnus et bien que l'organisation soit moins procédurale et unifiée, les droits des créatures y sont respectés et le secret est gardé.",
		'created_at' => NULL,'updated_at' => NULL
	]
];

$organisations_2 = [
	[
		'id' => "organisation_wo_hc",
		'name' => "Heirs of the Cardinal",
		'name_fr' => "Les Héritiers du Cardinal",
		'acronym' => "",
		'danger_level' => 2,
		'security_index' => -10,
		'part_of_ugb' => false,
		'countries' => ['WO'],
		'description' => "Organisation secrète ennemie à l'Ordre. Ses membres sont formés dès leur plus jeune âge afin de développer une mentalité pro-surnaturelle. Pour les humains, il s'agit souvent d'enfants kidnappés très jeunes. Ils sont ensuite envoyés pour infiltrer différentes agences en collaboration avec l'Ordre, à travers le monde. Chaque membre est dénommé par un code secret, et lié à une cellule dont il ne connaît pas nécessairement les autres membres. Les noms de codes et le nom de la cellule partagent un thème commun (par exemple, la cellule \"Minéraux\" pourrait comprendre des membres dénommés \"Quartz\", \"Grenat\", ou encore \"Opale\"). Ils ont une phrase pour se reconnaître entre eux s'ils doivent travailler à plusieurs. L'organisation est encadrée par les \"cinq élevés\" : le Veilleur Céleste, l'Observateur, le Soleil, le Premier Gardien et le Second Gardien. En-dessous d'eux, on trouve différentes fonctions chargées de diverses tâches spécifiques.",
		'created_at' => NULL,'updated_at' => NULL
	],
	[
		'id' => "organisation_mx_t",
		'name' => "Titlatollo",
		'name_fr' => "Nous Sommes l'Histoire",
		'acronym' => "",
		'danger_level' => 2,
		'security_index' => -12,
		'part_of_ugb' => false,
		'countries' => ['MX'],
		'description' => "Groupe réalisant des recherches historiques et dans le Monde des Esprits pour retracer l'histoire surnaturelle de la mésoamérique. Ils recherchent des créatures surnaturelles anciennes, principalement celles victimes de la colonisation espagnole de l'Amérique, puis justifient ensuite des actes criminels en disant vouloir rendre justice aux noms des victimes. Leur dicton est \"<span class='font-italic'>Yn imitolloca, yn imilnamicoca itic mictlanayahuitl</span>\" (nahuatl pour \"<span class='font-italic'>Leurs histoires, leurs mémoires dans le brouillard des morts</span>\").",
		'created_at' => NULL,'updated_at' => NULL
	],
	[
		'id' => "organisation_sv_gt_hn_pm",
		'name' => "Los Pañuelos Morados",
		'name_fr' => "Les Mouchoirs Violets",
		'acronym' => "",
		'danger_level' => 2,
		'security_index' => -50,
		'part_of_ugb' => false,
		'countries' => ['SV', 'GT', 'HN'],
		'description' => "ou simplement Los Morados (<span class='font-italic'>Les Violets</span>). Escadron de la mort ayant pour objectif d'exterminer le surnaturel. Ils contrôlent les territoires d'El Salvador, du Guatemala et de l'Honduras, où les organisations précédemment reconnues par l'Ordre ont été éliminées à force d'assassinats et d'attaques armées sur les agents. Les conflits aux frontières mexicaine, bélizienne et nicaraguayenne sont quasi-permanents puisque les Morados cherchent à étendre leur influence et à “libérer le Plan Terrestre” du surnaturel et de l'Ordre.",
		'created_at' => NULL,'updated_at' => NULL
	],
	[
		'id' => "organisation_cu_jmoo",
		'name' => "Junta Mundial Oculta Oprimida",
		'name_fr' => "Junte du Monde Caché Opprimé",
		'acronym' => "",
		'danger_level' => 2,
		'security_index' => -06,
		'part_of_ugb' => false,
		'countries' => ['CU'],
		'description' => "Alliance terroriste basée à Cuba mais ayant des membres dans plusieurs pays d'Amérique latine et quelques pays d'Afrique. Elle a pour objectif de soutenir les créatures cachées dans leur rébellion contre les autorités en place. Durant la guerre froide et le contexte des révolutions communistes qui ont mouvementé l'Amérique latine, plusieurs organisations supposées protéger le surnaturel ont commencé à utiliser les créatures cachées comme arme ou à les chasser à vue, selon les conflits. La junte avait pour objectif d'assurer un soutien mutuel logistique, financier et militaire aux communautés opprimées du Monde Caché afin qu'elles obtiennent elles-mêmes leur liberté. Dans les années 70s et 80s, elle a formé de nombreux groupes pro-surnaturels et organisé des assassinats et des tortures sur de nombreux membres des organisations faisant partie des <a class='orga_danger_0' data-orga-ref='organisation_wo_ugb'>UGB</a> (Groupes Unis pour l'Équilibre). Aujourd'hui, la junte n'est plus active et les quelques derniers membres se réfugient à Cuba. Elle reste cependant à surveiller.",
		'created_at' => NULL,'updated_at' => NULL
	],
	[
		'id' => "organisation_cl_dods",
		'name' => "Departamento de Operaciones de Defensa Sobrenatural",
		'name_fr' => "Service des Opérations de Défense contre le Surnaturel",
		'acronym' => "DODS",
		'danger_level' => 2,
		'security_index' => -10,
		'part_of_ugb' => false,
		'countries' => ['CL'],
		'description' => "Agence gouvernementale considérée comme terroriste, qui cherche à éradiquer le surnaturel du pays. Leurs ressources et présence sont aujourd'hui très faibles sur le pays, majoritairement géré par les <a class='orga_danger_0' data-orga-ref='organisation_cl_civs'>CIVS</a> avec qui ils sont en conflits permanents.",
		'created_at' => NULL,'updated_at' => NULL
	],
	[
		'id' => "organisation_co_sr",
		'name' => "La Sombra Roja",
		'name_fr' => "L'Ombre Rouge",
		'acronym' => "",
		'danger_level' => 2,
		'security_index' => -43,
		'part_of_ugb' => false,
		'countries' => ['CO'],
		'description' => "Groupe paramilitaire associé à un cartel de drogues. De 2003 à 2006, l'AUC (groupe paramilitaire d'extrême-droite) est dissoute mais plusieurs membres, opposés à cette entente avec le gouvernement, décident de créer leurs propres groupes paramilitaires. Parmi eux, la Sombra Roja qui dit protéger la population en appliquant une tolérance zéro sur les créatures surnaturelles à problème, en se passant de jugement. Les assassinats et les tortures font partie de ses pratiques courantes pour atteindre ses objectifs, même sur des humains. Il y a de plus un risque non négligeable que cette organisation commence à considérer l'usage du surnaturel dans leur cartel de drogue.",
		'created_at' => NULL,'updated_at' => NULL
	],
	[
		'id' => "organisation_br_ashs",
		'name' => "Agência de Segurança Humana Sobrenatural",
		'name_fr' => "Agence de Sécurité des Humains Surnaturels",
		'acronym' => "ASHS",
		'danger_level' => 1,
		'security_index' => 17,
		'part_of_ugb' => false,
		'countries' => ['BR'],
		'description' => "Agence gouvernementale chargée d’assurer la protection et l’accompagnement des humains liés au surnaturel. Au brésil, les humains pratiquant la magie ainsi que les humains transformés (tels que les loup-garous, les vampires ou les altérés) sont considérés comme des citoyens du pays. Ils peuvent également être employés au sein de l’ASHS. Les individus nés surnaturels, tels que les sorciers ou les fées, sont en revanche tout juste tolérés lors d’un passage dans le pays où ils ne sont pas considérés comme des citoyens. De fait, la relation entre l’ASHS et les <a class='orga_danger_0' data-orga-ref='organisation_br_sfd'>Sentinelas da Floresta Dourada</a> est délicate et très tendue. Le gouvernement brésilien n’offre aucune aide à la gestion de la Grande Réserve sur son pays, et essaie même de rendre son fonctionnement impossible. Mais ils sont principalement occupés par les <a class='orga_danger_2' data-orga-ref='organisation_br_sf'>Sem-Forma</a> qu’ils essaient de chasser hors du Brésil.",
		'created_at' => NULL,'updated_at' => NULL
	],
	[
		'id' => "organisation_br_sfd",
		'name' => "Sentinelas da Floresta Dourada",
		'name_fr' => "Sentinelles de la Forêt d'Or",
		'acronym' => "",
		'danger_level' => 0,
		'security_index' => 12,
		'part_of_ugb' => true,
		'countries' => ['BR'],
		'description' => "Les Sentinelles étaient originellement un groupe lié à l’El Dorado, bien qu’il soit incertain de savoir s’ils le cherchaient ou le protégeaient. Aujourd’hui, ils assurent le fonctionnement et la protection de la Grande Réserve Féerique du Brésil, qu’ils nomment “La Forêt d’Or”. Leur présence est contestée par l’<a class='orga_danger_1' data-orga-ref='organisation_br_ashs'>ASHS</a>, et bien qu’aucune opération violente n’ait été menée pour l’instant, les relations entre les deux organismes sont tendues.",
		'created_at' => NULL,'updated_at' => NULL
	],
	[
		'id' => "organisation_br_sf",
		'name' => "Sem-Forma",
		'name_fr' => "Les Sans-Forme",
		'acronym' => "",
		'danger_level' => 2,
		'security_index' => -27,
		'part_of_ugb' => false,
		'countries' => ['BR'],
		'description' => "Avec l’absence du Pilier et donc de Cercles sur l’entièreté du territoire du Brésil, des sorciers opposants au Pilier se sont organisés dans le pays, sous le nom des Sans-Forme. Ils luttent activement contre le Pilier, principalement dans les plans intermédiaires de ceux-ci sans tomber dans la juridiction d’aucune organisation terrestre. Outre leur lutte contre le Pilier, les membres ne sont pas organisés autour d’un autre objectif et chacun vit sa propre vie. Il s’agit principalement de criminels, s’adonnant à des activités illégales. Certains disent cependant agir pour la population et endossent des rôles inspirés des Super-héros de films. Tous considérés comme hors-la-loi par l’<a class='orga_danger_1' data-orga-ref='organisation_br_ashs'>ASHS</a>, ils sont pourchassés par celle-ci qui n’hésite pas à envoyer des altérés ou des vampires formés à la magie contre les Sans-Forme.",
		'created_at' => NULL,'updated_at' => NULL
	],
	[
		'id' => "organisation_bo_vue",
		'name' => "Vagabundos de la Undécima Estrella",
		'name_fr' => "Les Vagabonds de la Onzième Étoile",
		'acronym' => "",
		'danger_level' => 0,
		'security_index' => 36,
		'part_of_ugb' => true,
		'countries' => ['BO'],
		'description' => "ou juste La Undécima Estrella (La Onzième Etoile). Les nombreux coups d'État ayant eu lieu en Bolivie depuis son indépendance (190 coups entre 1825 et 1985) ont rendu impossible la gestion du surnaturel par l'État. L’organisme gouvernemental qui en était responsable sous l’empire espagnol a fini par s’en dissocier. La onzième étoile représente le Monde Caché de la Bolivie, une étoile absente de l’emblème du pays qui en contient une pour chacun de ses 10 départements. Pendant toutes ces années de mouvements politiques, les Vagabonds de la Onzième Étoile ont toujours su réagir rapidement et prévenir l’utilisation du surnaturel dans les différents conflits.",
		'created_at' => NULL,'updated_at' => NULL
	]
];

$organisations = array_merge($organisations_0, $organisations_1, $organisations_2);