<?php

$office_bosses = array(
    array(
		'id' => 'aaronbrand',
		'type' => 'human',
		'first_name' => 'Aaron',
		'last_name' => 'Brand',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '08/06/1971',
		'birth_place' => 'Beaumont, Texas, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_kansascity_ks',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'alexisjensen',
		'type' => 'human',
		'first_name' => 'Alexis',
		'last_name' => 'Jensen',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '22/08/1973',
		'birth_place' => 'La Cienega, Nouveau-Mexique, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_albuquerque_nm',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'andreduvall',
		'type' => 'human',
		'first_name' => 'Andre',
		'last_name' => 'Duvall',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '01/01/1980',
		'birth_place' => 'Johnstown, Pennsylvania, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_jackson_ms',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'arthurmatteson',
		'type' => 'human',
		'first_name' => 'Arthur',
		'last_name' => 'Matteson',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '23/02/1970',
		'birth_place' => 'Lake Shore, Maryland, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_milwaukee_wi',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'aubreyfaust',
		'type' => 'human',
		'first_name' => 'Aubrey',
		'last_name' => 'Faust',
		'aliases' => NULL,
		'sex' => 'female',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '19/11/1968',
		'birth_place' => 'Nashville, Tennessee, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_nashville_tn',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'aurelioconte',
		'type' => 'human',
		'first_name' => 'Aurelio',
		'last_name' => 'Conte',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '16/07/1992',
		'birth_place' => 'Yakima, Washington, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_spokane_wa',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'bonniesoria',
		'type' => 'human',
		'first_name' => 'Bonnie',
		'last_name' => 'Soria',
		'aliases' => NULL,
		'sex' => 'female',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '02/10/1974',
		'birth_place' => 'Fort Worth, Texas, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_odessa_tx',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'buddylambert',
		'type' => 'human',
		'first_name' => 'Buddy',
		'last_name' => 'Lambert',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '23/08/1977',
		'birth_place' => 'Oswego, New York, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_watertown_ny',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'clifffischer',
		'type' => 'human',
		'first_name' => 'Cliff',
		'last_name' => 'Fischer',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '28/08/1967',
		'birth_place' => 'Grafton, North Dakota, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_oklahomacity_ok',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'corrinalawsom',
		'type' => 'human',
		'first_name' => 'Corrina',
		'last_name' => 'Lawsom',
		'aliases' => NULL,
		'sex' => 'female',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '20/01/1954',
		'birth_place' => 'New York, New York, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_charlotte_nc',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'danielamcadams',
		'type' => 'human',
		'first_name' => 'Daniela',
		'last_name' => 'Mcadams',
		'aliases' => NULL,
		'sex' => 'female',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '13/07/1970',
		'birth_place' => 'Lake Los Angeles, Californie, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_casper_wy',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'devondevlin',
		'type' => 'human',
		'first_name' => 'Devon',
		'last_name' => 'Devlin',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '24/01/1981',
		'birth_place' => 'Roseville, Michigan, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_reno_nv',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'dominicbrowing',
		'type' => 'human',
		'first_name' => 'Dominic',
		'last_name' => 'Browing',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '03/07/1954',
		'birth_place' => 'East Hartford, Connecticut, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_littlerock_ar',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'donnellkelley',
		'type' => 'human',
		'first_name' => 'Donnell',
		'last_name' => 'Kelley',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '04/10/1978',
		'birth_place' => 'Tenafly, New Jersey, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_minneapolis_mn',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'earlaustin',
		'type' => 'human',
		'first_name' => 'Earl',
		'last_name' => 'Austin',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '01/08/1989',
		'birth_place' => 'Newark, Ohio, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_desmoines_ia',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'elliottsides',
		'type' => 'human',
		'first_name' => 'Elliott',
		'last_name' => 'Sides',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '12/09/1973',
		'birth_place' => 'Stansbury Park, Utah, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_detroit_mi',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'emileferry',
		'type' => 'human',
		'first_name' => 'Emile',
		'last_name' => 'Ferry',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '13/05/1976',
		'birth_place' => 'Garden Grove, Californie, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_portland_or',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'eribertocaballeros',
		'type' => 'human',
		'first_name' => 'Eriberto',
		'last_name' => 'Caballeros',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '16/06/1982',
		'birth_place' => 'Edmond, Oklahoma, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_chicago_il',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'erniecolon',
		'type' => 'human',
		'first_name' => 'Ernie',
		'last_name' => 'Colon',
		'aliases' => NULL,
		'sex' => 'female',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '12/03/1961',
		'birth_place' => 'Glasgow, Kentucky, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_saintlouis_mo',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'erolljewell',
		'type' => 'human',
		'first_name' => 'Eroll',
		'last_name' => 'Jewell',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '25/06/1988',
		'birth_place' => 'Fostoria, Ohio, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'black',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_siouxfalls_sd',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'estellastout',
		'type' => 'vampire',
		'first_name' => 'Estella',
		'last_name' => 'Stout',
		'aliases' => NULL,
		'sex' => 'female',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '13/11/1941',
		'birth_place' => NULL,
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'unknown',
		'status' => 'civilian',
		'languages' => 'Anglais',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => 'clan_lasvegas',
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'evelynmorrison',
		'type' => 'human',
		'first_name' => 'Evelyn',
		'last_name' => 'Morrison',
		'aliases' => 'Evelyn Morrison, Petit Coeur',
		'sex' => 'female',
		'height' => '173',
		'weight' => '89',
		'dead' => '0',
		'birth_date' => '13/03/1966',
		'birth_place' => 'Edmonton, Alberta, Canada',
		'hair' => 'Châtain',
		'eyes' => 'Marrons',
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais, Démoniaque',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'fabriceohara',
		'type' => 'human',
		'first_name' => 'Fabrice',
		'last_name' => 'Ohara',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '29/05/1982',
		'birth_place' => 'Wicklow, Irelande',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_charleston_sc',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'gerardoortega',
		'type' => 'human',
		'first_name' => 'Gerardo',
		'last_name' => 'Ortega',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '20/05/1965',
		'birth_place' => 'Utuado, Porto Rico',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'hispanic',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_sanjuan_pr',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'glencarver',
		'type' => 'human',
		'first_name' => 'Glen',
		'last_name' => 'Carver',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '15/12/1964',
		'birth_place' => 'Lincoln, Nebraska, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_seattle_wa',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'guylove',
		'type' => 'human',
		'first_name' => 'Guy',
		'last_name' => 'Love',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '16/01/1967',
		'birth_place' => 'Manteca, Californie, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_atlanta_ga',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'harryliwai',
		'type' => 'human',
		'first_name' => 'Harry',
		'last_name' => 'Liwai',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '21/12/1960',
		'birth_place' => 'Fremont, Californie, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'black',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_waikoloavillage_hi',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'herbertleroy',
		'type' => 'human',
		'first_name' => 'Herbert',
		'last_name' => 'Leroy',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '24/11/1976',
		'birth_place' => 'Richmond, Kentucky, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_miami_fl',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'jacecaldera',
		'type' => 'human',
		'first_name' => 'Jace',
		'last_name' => 'Caldera',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '03/11/1980',
		'birth_place' => 'Salinas, Californie, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_louisville_ky',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'jakesharp',
		'type' => 'human',
		'first_name' => 'Jake',
		'last_name' => 'Sharp',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '29/03/1966',
		'birth_place' => 'Arvada, Colorado, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_sanantonio_tx',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'janiewheeler',
		'type' => 'human',
		'first_name' => 'Janie',
		'last_name' => 'Wheeler',
		'aliases' => NULL,
		'sex' => 'female',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '15/07/1966',
		'birth_place' => 'Lee\'s Summit, Missouri, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'black',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_charleston_wv',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'jeffreycrisostomo',
		'type' => 'human',
		'first_name' => 'Jeffrey',
		'last_name' => 'Crisostomo',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '26/03/1982',
		'birth_place' => 'Hagåtña, Guam',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_hagatna_gu',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'jeremyfinch',
		'type' => 'human',
		'first_name' => 'Jeremy',
		'last_name' => 'Finch',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '21/05/1978',
		'birth_place' => 'Waco, Texas, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_dallas_tx',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'jimkirby',
		'type' => 'human',
		'first_name' => 'Jim',
		'last_name' => 'Kirby',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '27/11/1983',
		'birth_place' => 'Louisville, Colorado, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_philadelphie_pa',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'josephkyle',
		'type' => 'human',
		'first_name' => 'Joseph',
		'last_name' => 'Kyle',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '16/10/1964',
		'birth_place' => 'Los Angeles, Californie, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_birmingham_al',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'koberush',
		'type' => 'human',
		'first_name' => 'Kobe',
		'last_name' => 'Rush',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '17/02/1971',
		'birth_place' => 'Chicago, Illinois, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_colombus_oh',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'lanceleroy',
		'type' => 'human',
		'first_name' => 'Lance',
		'last_name' => 'Leroy',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '27/04/1973',
		'birth_place' => 'Decatur, Alabama, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_jacksonville_fl',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'lelandfeldman',
		'type' => 'human',
		'first_name' => 'Leland',
		'last_name' => 'Feldman',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '02/09/1964',
		'birth_place' => 'South Whittier, Californie, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_rapidcity_sd',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'leonsmith',
		'type' => 'human',
		'first_name' => 'Leon',
		'last_name' => 'Smith',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '25/11/1968',
		'birth_place' => 'New Braunfels, Texas, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_boise_id',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'lucylivingston',
		'type' => 'human',
		'first_name' => 'Lucy',
		'last_name' => 'Livingston',
		'aliases' => NULL,
		'sex' => 'female',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '06/05/1979',
		'birth_place' => 'Athens, Alabama, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_bismarck_nd',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'lukemast',
		'type' => 'human',
		'first_name' => 'Luke',
		'last_name' => 'Mast',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '28/05/1984',
		'birth_place' => 'Billings, Montana, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'black',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_billings_mt',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'mansirnwosu',
		'type' => 'human',
		'first_name' => 'Mansir',
		'last_name' => 'Nwosu',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '27/01/1973',
		'birth_place' => 'Nouvelle-Orléans, Louisiane, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'black',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_nouvelleorleans_la',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'marshallrichardson',
		'type' => 'human',
		'first_name' => 'Marshall',
		'last_name' => 'Richardson',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '18/08/1986',
		'birth_place' => 'Fountain Valley, Californie, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_dodgecity_ks',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'maurinerainey',
		'type' => 'human',
		'first_name' => 'Maurine',
		'last_name' => 'Rainey',
		'aliases' => NULL,
		'sex' => 'female',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '08/06/1985',
		'birth_place' => 'Saxon, Caroline du Sud, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais, Français',
		'place_id' => 'office_denver_co',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'michaelarchibald',
		'type' => 'human',
		'first_name' => 'Michael',
		'last_name' => 'Archibald',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '19/11/1976',
		'birth_place' => 'Sioux Falls, South Dakota, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_pittsburgh_pa',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'ngokdelong',
		'type' => 'human',
		'first_name' => 'Ngok',
		'last_name' => 'Delong',
		'aliases' => NULL,
		'sex' => 'female',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '01/09/1983',
		'birth_place' => 'Hòa Bình, Viêt Nam',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'asian',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_bangor_me',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'philippatten',
		'type' => 'human',
		'first_name' => 'Philip',
		'last_name' => 'Patten',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '14/05/1967',
		'birth_place' => 'Oak Grove, Texas, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_providence_ri',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'richworthy',
		'type' => 'human',
		'first_name' => 'Rich',
		'last_name' => 'Worthy',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '23/05/1977',
		'birth_place' => 'Anchorage, Alaska, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_anchorage_ak',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'rickeycornell',
		'type' => 'human',
		'first_name' => 'Rickey',
		'last_name' => 'Cornell',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '14/05/1967',
		'birth_place' => 'Baton Rouge, Louisiane, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'black',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_lynchburg_va',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'rupertnolan',
		'type' => 'human',
		'first_name' => 'Rupert',
		'last_name' => 'Nolan',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '24/10/1967',
		'birth_place' => 'Coachella, Californie, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_sanfrancisco_ca',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'ryanzamora',
		'type' => 'human',
		'first_name' => 'Ryan',
		'last_name' => 'Zamora',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '09/02/1990',
		'birth_place' => 'Glen Ellyn, Illinois, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_lincoln_ne',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'sheldonriggs',
		'type' => 'human',
		'first_name' => 'Sheldon',
		'last_name' => 'Riggs',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '22/02/1966',
		'birth_place' => 'New York, New York, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_newyork_ny',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'tomaspowell',
		'type' => 'human',
		'first_name' => 'Tomas',
		'last_name' => 'Powell',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '11/05/1974',
		'birth_place' => 'Los Angeles, Californie, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_losangeles_ca',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'trevorstarr',
		'type' => 'human',
		'first_name' => 'Trevor',
		'last_name' => 'Starr',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '26/06/1969',
		'birth_place' => 'Fish Hawk, Floride, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_saltlakecity_ut',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'tukkuttokapaata',
		'type' => 'human',
		'first_name' => 'Tukkuttok',
		'last_name' => 'Apaata',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '18/06/1978',
		'birth_place' => 'Huslia, Alaska, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'nativeamerican',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_anaktuvukpass_ak',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'tylorwalters',
		'type' => 'human',
		'first_name' => 'Tylor',
		'last_name' => 'Walters',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '10/03/1965',
		'birth_place' => 'Shepherdsville, Kentucky, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_washington_dc',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'wanaaopekelo',
		'type' => 'human',
		'first_name' => 'Wana\'ao',
		'last_name' => 'Pekelo',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '18/02/1972',
		'birth_place' => 'Honolulu, Hawaii, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'black',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_honolulu_hi',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'willardelsmore',
		'type' => 'human',
		'first_name' => 'Willard',
		'last_name' => 'Elsmore',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '30/06/1972',
		'birth_place' => 'Mesa, Arizona, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_phoenix_az',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'willisweldon',
		'type' => 'human',
		'first_name' => 'Willis',
		'last_name' => 'Weldon',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '13/01/1970',
		'birth_place' => 'Midvale, Utah, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_indianapolis_in',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

);

$hunters = array(
    array(
		'id' => 'aleccohensarajevic',
		'type' => 'human',
		'first_name' => 'Alec',
		'last_name' => 'Cohen Sarajevic',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '30/05/1978',
		'birth_place' => 'Kragujevac, Yougoslavie',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'veraframirez',
		'type' => 'human',
		'first_name' => 'Vera',
		'last_name' => 'F. Ramirez',
		'aliases' => NULL,
		'sex' => 'female',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '15/06/1968',
		'birth_place' => 'Tucson Estates, Arizona, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'hispanic',
		'status' => 'agent',
		'languages' => 'Anglais, Espagnole',
		'place_id' => 'office_phoenix_az',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

);

$vampires = array(
    array(
		'id' => 'abbycordwell',
		'type' => 'vampire',
		'first_name' => 'Abbigail',
		'last_name' => 'Cordwell',
		'aliases' => 'Abbigail Cordwell, Abby',
		'sex' => 'female',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '13/06/1996',
		'birth_place' => NULL,
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'unknown',
		'status' => 'civilian',
		'languages' => 'Anglais',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => 'clan_lasvegas',
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'birdietate',
		'type' => 'vampire',
		'first_name' => 'Birdie',
		'last_name' => 'Tate',
		'aliases' => NULL,
		'sex' => 'female',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '26/03/1940',
		'birth_place' => NULL,
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'unknown',
		'status' => 'civilian',
		'languages' => 'Anglais',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => 'clan_lasvegas',
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'calebmagnar',
		'type' => 'vampire',
		'first_name' => 'Caleb',
		'last_name' => 'Magnar',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '1',
		'birth_date' => '08/05/1760',
		'birth_place' => NULL,
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'unknown',
		'status' => 'civilian',
		'languages' => 'Anglais',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => 'clan_lasvegas',
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'calvinbeck',
		'type' => 'vampire',
		'first_name' => 'Calvin',
		'last_name' => 'Beck',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '10/11/1918',
		'birth_place' => NULL,
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'unknown',
		'status' => 'civilian',
		'languages' => 'Anglais',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => 'clan_lasvegas',
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'celosia',
		'type' => 'vampire',
		'first_name' => '',
		'last_name' => 'Celosia',
		'aliases' => NULL,
		'sex' => 'female',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '1',
		'birth_date' => '17/09/1895',
		'birth_place' => NULL,
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'unknown',
		'status' => 'civilian',
		'languages' => 'Anglais',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => 'clan_lasvegas',
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'charlesgates',
		'type' => 'vampire',
		'first_name' => 'Charles',
		'last_name' => 'Gates',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '19/09/1975',
		'birth_place' => NULL,
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'unknown',
		'status' => 'prisoner',
		'languages' => 'Anglais',
		'place_id' => 'prison_moreypeak_nv',
		'group_id' => 'clan_lasvegas',
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'leonardopezziali',
		'type' => 'vampire',
		'first_name' => 'Leonardo',
		'last_name' => 'Pezziali',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '14/08/1755',
		'birth_place' => NULL,
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'unknown',
		'status' => 'civilian',
		'languages' => 'Anglais',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => 'clan_lasvegas',
		'sire_id' => NULL,
		'self_control' => '1',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'margaretlowery',
		'type' => 'vampire',
		'first_name' => 'Margaret',
		'last_name' => 'Lowery',
		'aliases' => NULL,
		'sex' => 'female',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '12/12/1756',
		'birth_place' => NULL,
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'unknown',
		'status' => 'civilian',
		'languages' => 'Anglais, Français, Créole haïtien, Italien',
		'place_id' => 'office_nouvelleorleans_la',
		'group_id' => 'clan_nouvelleorleans_la',
		'sire_id' => NULL,
		'self_control' => '1',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'martinclayton',
		'type' => 'vampire',
		'first_name' => 'Martin',
		'last_name' => 'Clayton',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '12/01/1941',
		'birth_place' => NULL,
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'unknown',
		'status' => 'civilian',
		'languages' => 'Anglais',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => 'clan_lasvegas',
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'maudgriffith',
		'type' => 'vampire',
		'first_name' => 'Maud',
		'last_name' => 'Griffith',
		'aliases' => NULL,
		'sex' => 'female',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '15/12/1960',
		'birth_place' => NULL,
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'unknown',
		'status' => 'civilian',
		'languages' => 'Anglais',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => 'clan_lasvegas',
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'vernonlangley',
		'type' => 'vampire',
		'first_name' => 'Vernon',
		'last_name' => 'Langley',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '1',
		'birth_date' => '14/02/1667',
		'birth_place' => NULL,
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'unknown',
		'status' => 'civilian',
		'languages' => 'Anglais, Français',
		'place_id' => 'office_losangeles_ca',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'williamadan',
		'type' => 'vampire',
		'first_name' => 'William',
		'last_name' => 'Adan',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '05/02/1799',
		'birth_place' => NULL,
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'unknown',
		'status' => 'civilian',
		'languages' => 'Anglais, Russe, Français, Espagnol, Algonquin',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => 'clan_lasvegas',
		'sire_id' => NULL,
		'self_control' => '1',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),
);

$warlocks = array(
    array(
		'id' => 'adenmcguire',
		'type' => 'warlock',
		'first_name' => 'Aden',
		'last_name' => 'McGuire',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '12/04/1753',
		'birth_place' => NULL,
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'unknown',
		'status' => 'civilian',
		'languages' => 'Anglais',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => 'circle_lasvegas',
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'coreyhunt',
		'type' => 'warlock',
		'first_name' => 'Corey',
		'last_name' => 'Hunt',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '11/09/1813',
		'birth_place' => NULL,
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'unknown',
		'status' => 'civilian',
		'languages' => 'Anglais',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => 'circle_lasvegas',
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'dagandevante',
		'type' => 'warlock',
		'first_name' => 'Dagan',
		'last_name' => 'Devante',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '01/01/1261',
		'birth_place' => NULL,
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'unknown',
		'status' => 'civilian',
		'languages' => 'Anglais',
		'place_id' => 'office_phoenix_az',
		'group_id' => 'circle_phoenix',
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'kharakroshan',
		'type' => 'warlock',
		'first_name' => 'Kharak',
		'last_name' => 'Roshan',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '01/01/-1500',
		'birth_place' => NULL,
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'unknown',
		'status' => 'civilian',
		'languages' => 'Anglais',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => 'circle_lasvegas',
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'riverlee',
		'type' => 'warlock',
		'first_name' => 'River',
		'last_name' => 'Lee',
		'aliases' => NULL,
		'sex' => 'female',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '15/12/1435',
		'birth_place' => NULL,
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'unknown',
		'status' => 'civilian',
		'languages' => 'Anglais',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => 'circle_lasvegas',
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'sharonkennedy',
		'type' => 'warlock',
		'first_name' => 'Sharon',
		'last_name' => 'Kennedy',
		'aliases' => NULL,
		'sex' => 'female',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '05/10/1930',
		'birth_place' => NULL,
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'unknown',
		'status' => 'prisoner',
		'languages' => 'Anglais',
		'place_id' => 'prison_moreypeak_nv',
		'group_id' => 'circle_lasvegas',
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),
);

$werewolves = array(
    array(
		'id' => 'alliehooper',
		'type' => 'werewolf',
		'first_name' => 'Allie',
		'last_name' => 'Hooper',
		'aliases' => NULL,
		'sex' => 'female',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '10/02/2006',
		'birth_place' => NULL,
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'unknown',
		'status' => 'civilian',
		'languages' => 'Anglais',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => 'pack_griffesdevegas',
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'anthonyhooper',
		'type' => 'werewolf',
		'first_name' => 'Anthony',
		'last_name' => 'Hooper',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '21/04/1976',
		'birth_place' => NULL,
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'unknown',
		'status' => 'civilian',
		'languages' => 'Anglais',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => 'pack_griffesdevegas',
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'bessodell',
		'type' => 'werewolf',
		'first_name' => 'Bess',
		'last_name' => 'Odell',
		'aliases' => NULL,
		'sex' => 'female',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '25/05/1981',
		'birth_place' => NULL,
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'unknown',
		'status' => 'civilian',
		'languages' => 'Anglais',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => 'pack_griffesdevegas',
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'declansamson',
		'type' => 'werewolf',
		'first_name' => 'Declan',
		'last_name' => 'Samson',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '03/02/1977',
		'birth_place' => NULL,
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'unknown',
		'status' => 'prisoner',
		'languages' => 'Anglais, Français',
		'place_id' => 'prison_homochitto_ms',
		'group_id' => 'pack_nouvelleorleans_la',
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'garrettstafford',
		'type' => 'werewolf',
		'first_name' => 'Garrett',
		'last_name' => 'Stafford',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '15/12/1980',
		'birth_place' => NULL,
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'unknown',
		'status' => 'prisoner',
		'languages' => 'Anglais',
		'place_id' => 'prison_moreypeak_nv',
		'group_id' => 'pack_fullmoonriders',
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'jacksoncox',
		'type' => 'werewolf',
		'first_name' => 'Jackson',
		'last_name' => 'Cox',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '03/02/1977',
		'birth_place' => NULL,
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'unknown',
		'status' => 'civilian',
		'languages' => 'Anglais',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => 'pack_griffesdevegas',
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'jordanyeriva',
		'type' => 'werewolf',
		'first_name' => 'Jordan',
		'last_name' => 'Yeriva',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '15/12/1987',
		'birth_place' => NULL,
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'unknown',
		'status' => 'prisoner',
		'languages' => 'Anglais, Bulgare',
		'place_id' => 'prison_moreypeak_nv',
		'group_id' => 'pack_fullmoonriders',
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'kendricktendor',
		'type' => 'werewolf',
		'first_name' => 'Kendrick',
		'last_name' => 'Tendor',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '28/07/1953',
		'birth_place' => NULL,
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'unknown',
		'status' => 'civilian',
		'languages' => 'Anglais',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => 'pack_griffesdevegas',
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'lucilledotson',
		'type' => 'werewolf',
		'first_name' => 'Lucille',
		'last_name' => 'Dotson',
		'aliases' => NULL,
		'sex' => 'female',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '02/08/1965',
		'birth_place' => NULL,
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'unknown',
		'status' => 'civilian',
		'languages' => 'Anglais',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => 'pack_griffesdevegas',
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'noragibbons',
		'type' => 'werewolf',
		'first_name' => 'Nora',
		'last_name' => 'Gibbons',
		'aliases' => NULL,
		'sex' => 'female',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '13/09/1961',
		'birth_place' => NULL,
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'unknown',
		'status' => 'civilian',
		'languages' => 'Anglais',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => 'pack_griffesdevegas',
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'ozzywade',
		'type' => 'werewolf',
		'first_name' => 'Ozzy',
		'last_name' => 'Wade',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '21/03/1962',
		'birth_place' => NULL,
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'unknown',
		'status' => 'civilian',
		'languages' => 'Anglais, Féérique, Démoniaque',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => 'pack_griffesdevegas',
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'royturner',
		'type' => 'werewolf',
		'first_name' => 'Roy',
		'last_name' => 'Turner',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '13/06/1986',
		'birth_place' => NULL,
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'unknown',
		'status' => 'prisoner',
		'languages' => 'Anglais, Serbe',
		'place_id' => 'prison_moreypeak_nv',
		'group_id' => 'pack_fullmoonriders',
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'victormooney',
		'type' => 'werewolf',
		'first_name' => 'Victor',
		'last_name' => 'Mooney',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '10/11/1968',
		'birth_place' => NULL,
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'unknown',
		'status' => 'civilian',
		'languages' => 'Anglais',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => 'pack_griffesdevegas',
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'zoechapman',
		'type' => 'werewolf',
		'first_name' => 'Zoe',
		'last_name' => 'Chapman',
		'aliases' => NULL,
		'sex' => 'female',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '30/06/1983',
		'birth_place' => NULL,
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'unknown',
		'status' => 'prisoner',
		'languages' => 'Anglais',
		'place_id' => 'prison_moreypeak_nv',
		'group_id' => 'pack_fullmoonriders',
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
    ),
);

$wanteds = array(
    array(
		'id' => 'basrielnix',
		'type' => 'human',
		'first_name' => 'Basriel',
		'last_name' => 'Nix',
		'aliases' => 'Basriel Nix',
		'sex' => 'male',
		'height' => '191',
		'weight' => '85',
		'dead' => '0',
		'birth_date' => '06/06/1996',
		'birth_place' => 'Nouveau-Mexique, Etats-Unis',
		'hair' => 'Noirs',
		'eyes' => 'Marron',
		'ethnic_group' => 'white',
		'status' => 'wanted',
		'languages' => 'Anglais, Démoniaque (supposé)',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'claytonmoore',
		'type' => 'human',
		'first_name' => 'Clayton',
		'last_name' => 'Moore',
		'aliases' => 'Clayton Moore, Le Doc, Docteur',
		'sex' => 'male',
		'height' => '182',
		'weight' => '81',
		'dead' => '0',
		'birth_date' => '30/05/1970',
		'birth_place' => 'Athens, Georgie, Etats-Unis',
		'hair' => 'Chatain',
		'eyes' => 'Bleus',
		'ethnic_group' => 'white',
		'status' => 'wanted',
		'languages' => 'Anglais, Allemand, Espagnol',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'hommemasque',
		'type' => 'unknown',
		'first_name' => 'L\'',
		'last_name' => 'Homme Masqué',
		'aliases' => 'L\'Homme Masqué',
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => NULL,
		'birth_place' => NULL,
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'unknown',
		'status' => 'wanted',
		'languages' => 'Anglais',
		'place_id' => 'office_newyork_ny',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'leslielohflower',
		'type' => 'werewolf',
		'first_name' => 'Leslie',
		'last_name' => 'Lohflower',
		'aliases' => 'Leslie Lohflower',
		'sex' => 'male',
		'height' => '188',
		'weight' => '88',
		'dead' => '0',
		'birth_date' => '16/09/1995',
		'birth_place' => 'Santa Barbara, Californie, Etats-Unis',
		'hair' => 'Blond',
		'eyes' => 'Bleus',
		'ethnic_group' => 'white',
		'status' => 'wanted',
		'languages' => 'Anglais',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => 'pack_fullmoonriders',
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'micahfuchs',
		'type' => 'werewolf',
		'first_name' => 'Micah',
		'last_name' => 'Fuchs',
		'aliases' => 'Micah Fuchs',
		'sex' => 'male',
		'height' => '188',
		'weight' => '88',
		'dead' => '0',
		'birth_date' => '22/03/1996',
		'birth_place' => 'Cedar City, Utah, Etats-Unis',
		'hair' => 'Blond',
		'eyes' => 'Bleus',
		'ethnic_group' => 'white',
		'status' => 'wanted',
		'languages' => 'Anglais',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => 'pack_fullmoonriders',
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),

    array(
		'id' => 'otto',
		'type' => 'warlock',
		'first_name' => 'Otto',
		'last_name' => '',
		'aliases' => 'Otto',
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => NULL,
		'birth_place' => NULL,
		'hair' => 'Blond',
		'eyes' => 'Vert',
		'ethnic_group' => 'white',
		'status' => 'wanted',
		'languages' => 'Anglais',
		'place_id' => 'office_newyork_ny',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
		'created_at' => NULL,
		'updated_at' => NULL
	),
);