<?php

$office_bosses = [
	// Aaron Brand
    [
		'id' => 'aaronbrand',
		'type' => 'human',
		'first_name' => 'Aaron',
		'last_name' => 'Brand',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '08/06/1971',
		'birth_place' => 'Beaumont, Texas, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_kansascity_ks',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Alexis Jensen
    [
		'id' => 'alexisjensen',
		'type' => 'human',
		'first_name' => 'Alexis',
		'last_name' => 'Jensen',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '22/08/1973',
		'birth_place' => 'La Cienega, Nouveau-Mexique, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_albuquerque_nm',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Andre Duvall
    [
		'id' => 'andreduvall',
		'type' => 'human',
		'first_name' => 'Andre',
		'last_name' => 'Duvall',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '01/01/1980',
		'birth_place' => 'Johnstown, Pennsylvania, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_jackson_ms',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Arthur Matteson
    [
		'id' => 'arthurmatteson',
		'type' => 'human',
		'first_name' => 'Arthur',
		'last_name' => 'Matteson',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '23/02/1970',
		'birth_place' => 'Lake Shore, Maryland, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_milwaukee_wi',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Aubrey Faust
    [
		'id' => 'aubreyfaust',
		'type' => 'human',
		'first_name' => 'Aubrey',
		'last_name' => 'Faust',
		'aliases' => NULL,
		'sex' => 'female',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '19/11/1968',
		'birth_place' => 'Nashville, Tennessee, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_nashville_tn',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Aurelio Conte
    [
		'id' => 'aurelioconte',
		'type' => 'human',
		'first_name' => 'Aurelio',
		'last_name' => 'Conte',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '16/07/1992',
		'birth_place' => 'Yakima, Washington, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_spokane_wa',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Bonnie Soria
    [
		'id' => 'bonniesoria',
		'type' => 'human',
		'first_name' => 'Bonnie',
		'last_name' => 'Soria',
		'aliases' => NULL,
		'sex' => 'female',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '02/10/1974',
		'birth_place' => 'Fort Worth, Texas, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_odessa_tx',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Buddy Lambert
    [
		'id' => 'buddylambert',
		'type' => 'human',
		'first_name' => 'Buddy',
		'last_name' => 'Lambert',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '23/08/1977',
		'birth_place' => 'Oswego, New York, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_watertown_ny',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Cliff Fischer
    [
		'id' => 'clifffischer',
		'type' => 'human',
		'first_name' => 'Cliff',
		'last_name' => 'Fischer',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '28/08/1967',
		'birth_place' => 'Grafton, North Dakota, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_oklahomacity_ok',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Corrina Lawsom
    [
		'id' => 'corrinalawsom',
		'type' => 'human',
		'first_name' => 'Corrina',
		'last_name' => 'Lawsom',
		'aliases' => NULL,
		'sex' => 'female',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '20/01/1954',
		'birth_place' => 'New York, New York, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_charlotte_nc',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Daniela Mcadams
    [
		'id' => 'danielamcadams',
		'type' => 'human',
		'first_name' => 'Daniela',
		'last_name' => 'Mcadams',
		'aliases' => NULL,
		'sex' => 'female',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '13/07/1970',
		'birth_place' => 'Lake Los Angeles, Californie, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_casper_wy',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Saul Hopper
    [
		'id' => 'saulhopper',
		'type' => 'human',
		'first_name' => 'Saul',
		'last_name' => 'Hopper',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '24/01/1981',
		'birth_place' => 'Roseville, Michigan, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_reno_nv',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Dominic Browing
    [
		'id' => 'dominicbrowing',
		'type' => 'human',
		'first_name' => 'Dominic',
		'last_name' => 'Browing',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '03/07/1954',
		'birth_place' => 'East Hartford, Connecticut, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_littlerock_ar',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Donnell Kelley
    [
		'id' => 'donnellkelley',
		'type' => 'human',
		'first_name' => 'Donnell',
		'last_name' => 'Kelley',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '04/10/1978',
		'birth_place' => 'Tenafly, New Jersey, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_minneapolis_mn',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Earl Austin
    [
		'id' => 'earlaustin',
		'type' => 'human',
		'first_name' => 'Earl',
		'last_name' => 'Austin',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '01/08/1989',
		'birth_place' => 'Newark, Ohio, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_desmoines_ia',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Elliott Sides
    [
		'id' => 'elliottsides',
		'type' => 'human',
		'first_name' => 'Elliott',
		'last_name' => 'Sides',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '12/09/1973',
		'birth_place' => 'Stansbury Park, Utah, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_detroit_mi',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Emile Ferry
    [
		'id' => 'emileferry',
		'type' => 'human',
		'first_name' => 'Emile',
		'last_name' => 'Ferry',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '13/05/1976',
		'birth_place' => 'Garden Grove, Californie, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_portland_or',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Eriberto Caballeros
    [
		'id' => 'eribertocaballeros',
		'type' => 'human',
		'first_name' => 'Eriberto',
		'last_name' => 'Caballeros',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '16/06/1982',
		'birth_place' => 'Edmond, Oklahoma, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_chicago_il',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Ernie Colon
    [
		'id' => 'erniecolon',
		'type' => 'human',
		'first_name' => 'Ernie',
		'last_name' => 'Colon',
		'aliases' => NULL,
		'sex' => 'female',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '12/03/1961',
		'birth_place' => 'Glasgow, Kentucky, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_saintlouis_mo',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Eroll Jewell
    [
		'id' => 'erolljewell',
		'type' => 'human',
		'first_name' => 'Eroll',
		'last_name' => 'Jewell',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '25/06/1988',
		'birth_place' => 'Fostoria, Ohio, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'black',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_siouxfalls_sd',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Evelyn Morrison
    [
		'id' => 'evelynmorrison',
		'type' => 'human',
		'first_name' => 'Evelyn',
		'last_name' => 'Morrison',
		'aliases' => 'Evelyn Morrison, Petit Coeur',
		'sex' => 'female',
		'height' => '173',
		'weight' => '89',
		'dead' => '0',
		'birth_date' => '13/03/1966',
		'birth_place' => 'Edmonton, Alberta, Canada',
		'hair' => 'Châtain',
		'eyes' => 'Marrons',
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais, Démoniaque',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Fabrice Ohara
    [
		'id' => 'fabriceohara',
		'type' => 'human',
		'first_name' => 'Fabrice',
		'last_name' => 'Ohara',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '29/05/1982',
		'birth_place' => 'Wicklow, Irelande',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_charleston_sc',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Gerardo Ortega
    [
		'id' => 'gerardoortega',
		'type' => 'human',
		'first_name' => 'Gerardo',
		'last_name' => 'Ortega',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '20/05/1965',
		'birth_place' => 'Utuado, Porto Rico',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'hispanic',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_sanjuan_pr',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Glen Carver
    [
		'id' => 'glencarver',
		'type' => 'human',
		'first_name' => 'Glen',
		'last_name' => 'Carver',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '15/12/1964',
		'birth_place' => 'Lincoln, Nebraska, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_seattle_wa',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Guy Love
    [
		'id' => 'guylove',
		'type' => 'human',
		'first_name' => 'Guy',
		'last_name' => 'Love',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '16/01/1967',
		'birth_place' => 'Manteca, Californie, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_atlanta_ga',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Harry Liwai
    [
		'id' => 'harryliwai',
		'type' => 'human',
		'first_name' => 'Harry',
		'last_name' => 'Liwai',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '21/12/1960',
		'birth_place' => 'Fremont, Californie, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'black',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_waikoloavillage_hi',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Herbert Leroy
    [
		'id' => 'herbertleroy',
		'type' => 'human',
		'first_name' => 'Herbert',
		'last_name' => 'Leroy',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '24/11/1976',
		'birth_place' => 'Richmond, Kentucky, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_miami_fl',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Jace Caldera
    [
		'id' => 'jacecaldera',
		'type' => 'human',
		'first_name' => 'Jace',
		'last_name' => 'Caldera',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '03/11/1980',
		'birth_place' => 'Salinas, Californie, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_louisville_ky',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Jake Sharp
    [
		'id' => 'jakesharp',
		'type' => 'human',
		'first_name' => 'Jake',
		'last_name' => 'Sharp',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '29/03/1966',
		'birth_place' => 'Arvada, Colorado, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_sanantonio_tx',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Janie Wheeler
    [
		'id' => 'janiewheeler',
		'type' => 'human',
		'first_name' => 'Janie',
		'last_name' => 'Wheeler',
		'aliases' => NULL,
		'sex' => 'female',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '15/07/1966',
		'birth_place' => 'Lee\'s Summit, Missouri, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'black',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_charleston_wv',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Jeffrey Crisostomo
    [
		'id' => 'jeffreycrisostomo',
		'type' => 'human',
		'first_name' => 'Jeffrey',
		'last_name' => 'Crisostomo',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '26/03/1982',
		'birth_place' => 'Hagåtña, Guam',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_hagatna_gu',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Jeremy Finch
    [
		'id' => 'jeremyfinch',
		'type' => 'human',
		'first_name' => 'Jeremy',
		'last_name' => 'Finch',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '21/05/1978',
		'birth_place' => 'Waco, Texas, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_dallas_tx',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Jim Kirby
    [
		'id' => 'jimkirby',
		'type' => 'human',
		'first_name' => 'Jim',
		'last_name' => 'Kirby',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '27/11/1983',
		'birth_place' => 'Louisville, Colorado, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_philadelphie_pa',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Joseph Kyle
    [
		'id' => 'josephkyle',
		'type' => 'human',
		'first_name' => 'Joseph',
		'last_name' => 'Kyle',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '16/10/1964',
		'birth_place' => 'Los Angeles, Californie, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_birmingham_al',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Kobe Rush
    [
		'id' => 'koberush',
		'type' => 'human',
		'first_name' => 'Kobe',
		'last_name' => 'Rush',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '17/02/1971',
		'birth_place' => 'Chicago, Illinois, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_colombus_oh',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Lance Leroy
    [
		'id' => 'lanceleroy',
		'type' => 'human',
		'first_name' => 'Lance',
		'last_name' => 'Leroy',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '27/04/1973',
		'birth_place' => 'Decatur, Alabama, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_jacksonville_fl',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Leland Feldman
    [
		'id' => 'lelandfeldman',
		'type' => 'human',
		'first_name' => 'Leland',
		'last_name' => 'Feldman',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '02/09/1964',
		'birth_place' => 'South Whittier, Californie, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_rapidcity_sd',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Leon Smith
    [
		'id' => 'leonsmith',
		'type' => 'human',
		'first_name' => 'Leon',
		'last_name' => 'Smith',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '25/11/1968',
		'birth_place' => 'New Braunfels, Texas, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_boise_id',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Lucy Livingston
    [
		'id' => 'lucylivingston',
		'type' => 'human',
		'first_name' => 'Lucy',
		'last_name' => 'Livingston',
		'aliases' => NULL,
		'sex' => 'female',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '06/05/1979',
		'birth_place' => 'Athens, Alabama, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_bismarck_nd',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Luke Mast
    [
		'id' => 'lukemast',
		'type' => 'human',
		'first_name' => 'Luke',
		'last_name' => 'Mast',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '28/05/1984',
		'birth_place' => 'Billings, Montana, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'black',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_billings_mt',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Mansir Nwosu
    [
		'id' => 'mansirnwosu',
		'type' => 'human',
		'first_name' => 'Mansir',
		'last_name' => 'Nwosu',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '27/01/1973',
		'birth_place' => 'Nouvelle-Orléans, Louisiane, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'black',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_nouvelleorleans_la',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Marshall Richardson
    [
		'id' => 'marshallrichardson',
		'type' => 'human',
		'first_name' => 'Marshall',
		'last_name' => 'Richardson',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '18/08/1986',
		'birth_place' => 'Fountain Valley, Californie, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_dodgecity_ks',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Maurine Riley
    [
		'id' => 'maurinerainey',
		'type' => 'human',
		'first_name' => 'Maurine',
		'last_name' => 'Rainey',
		'aliases' => NULL,
		'sex' => 'female',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '08/06/1985',
		'birth_place' => 'Saxon, Caroline du Sud, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais, Français',
		'place_id' => 'office_denver_co',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Michel Archibald
    [
		'id' => 'michaelarchibald',
		'type' => 'human',
		'first_name' => 'Michael',
		'last_name' => 'Archibald',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '19/11/1976',
		'birth_place' => 'Sioux Falls, South Dakota, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_pittsburgh_pa',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Ngok Delong
    [
		'id' => 'ngokdelong',
		'type' => 'human',
		'first_name' => 'Ngok',
		'last_name' => 'Delong',
		'aliases' => NULL,
		'sex' => 'female',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '01/09/1983',
		'birth_place' => 'Hòa Bình, Viêt Nam',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'asian',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_bangor_me',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Philip Patten
    [
		'id' => 'philippatten',
		'type' => 'human',
		'first_name' => 'Philip',
		'last_name' => 'Patten',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '14/05/1967',
		'birth_place' => 'Oak Grove, Texas, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_providence_ri',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Rich Worthy
    [
		'id' => 'richworthy',
		'type' => 'human',
		'first_name' => 'Rich',
		'last_name' => 'Worthy',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '23/05/1977',
		'birth_place' => 'Anchorage, Alaska, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_anchorage_ak',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Rickey Cornell
    [
		'id' => 'rickeycornell',
		'type' => 'human',
		'first_name' => 'Rickey',
		'last_name' => 'Cornell',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '14/05/1967',
		'birth_place' => 'Baton Rouge, Louisiane, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'black',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_lynchburg_va',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Rupert Nolan
    [
		'id' => 'rupertnolan',
		'type' => 'human',
		'first_name' => 'Rupert',
		'last_name' => 'Nolan',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '24/10/1967',
		'birth_place' => 'Coachella, Californie, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_sanfrancisco_ca',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Ryan Zamora
    [
		'id' => 'ryanzamora',
		'type' => 'human',
		'first_name' => 'Ryan',
		'last_name' => 'Zamora',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '09/02/1990',
		'birth_place' => 'Glen Ellyn, Illinois, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_lincoln_ne',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Sheldon Riggs
    [
		'id' => 'sheldonriggs',
		'type' => 'human',
		'first_name' => 'Sheldon',
		'last_name' => 'Riggs',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '22/02/1966',
		'birth_place' => 'New York, New York, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_newyork_ny',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Tomas Powell
    [
		'id' => 'tomaspowell',
		'type' => 'human',
		'first_name' => 'Tomas',
		'last_name' => 'Powell',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '11/05/1974',
		'birth_place' => 'Los Angeles, Californie, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_losangeles_ca',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Trevor Starr
    [
		'id' => 'trevorstarr',
		'type' => 'human',
		'first_name' => 'Trevor',
		'last_name' => 'Starr',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '26/06/1969',
		'birth_place' => 'Fish Hawk, Floride, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_saltlakecity_ut',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Tukkuttok Apaata
    [
		'id' => 'tukkuttokapaata',
		'type' => 'human',
		'first_name' => 'Tukkuttok',
		'last_name' => 'Apaata',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '18/06/1978',
		'birth_place' => 'Huslia, Alaska, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'nativeamerican',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_anaktuvukpass_ak',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Tylor Walters
    [
		'id' => 'tylorwalters',
		'type' => 'human',
		'first_name' => 'Tylor',
		'last_name' => 'Walters',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '10/03/1965',
		'birth_place' => 'Shepherdsville, Kentucky, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_washington_dc',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Wana'ao Pekelo
    [
		'id' => 'wanaaopekelo',
		'type' => 'human',
		'first_name' => 'Wana\'ao',
		'last_name' => 'Pekelo',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '18/02/1972',
		'birth_place' => 'Honolulu, Hawaii, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'black',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_honolulu_hi',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Willard Elsmore
    [
		'id' => 'willardelsmore',
		'type' => 'human',
		'first_name' => 'Willard',
		'last_name' => 'Elsmore',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '30/06/1972',
		'birth_place' => 'Mesa, Arizona, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_phoenix_az',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Willis Weldon
    [
		'id' => 'willisweldon',
		'type' => 'human',
		'first_name' => 'Willis',
		'last_name' => 'Weldon',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '13/01/1970',
		'birth_place' => 'Midvale, Utah, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_indianapolis_in',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

];

$hunters = [
	// Alec Cohen Sarajevic
    [
		'id' => 'aleccohensarajevic',
		'type' => 'human',
		'first_name' => 'Alec',
		'last_name' => 'Cohen Sarajevic',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '30/05/1978',
		'birth_place' => 'Kragujevac, Yougoslavie',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],
	
	// Nathaniel Lancaster
    [
		'id' => 'nathaniellancaster',
		'type' => 'human',
		'first_name' => 'Nathaniel',
		'last_name' => 'Lancaster',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => 180,
		'weight' => 80,
		'dead' => '0',
		'birth_date' => '16/08/1986',
		'birth_place' => 'Liverpool, Angleterre',
		'hair' => "Blonds",
		'eyes' => "Marrons",
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],
	
	// Doyle Carter
    [
		'id' => 'doylecarter',
		'type' => 'human',
		'first_name' => 'Doyle',
		'last_name' => 'Carter',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => 175,
		'weight' => 67,
		'dead' => '0',
		'birth_date' => '31/10/1971',
		'birth_place' => 'Dallas, Texas, Etats-Unis',
		'hair' => "Bruns",
		'eyes' => "Gris",
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],
	
	// Gael Jestin
    [
		'id' => 'gaeljestin',
		'type' => 'human',
		'first_name' => 'Gael',
		'last_name' => 'Jestin',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => 175,
		'weight' => 66,
		'dead' => '0',
		'birth_date' => '10/10/1994',
		'birth_place' => 'France',
		'hair' => "Noirs",
		'eyes' => "Bleus",
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais, Français, Breton',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],
	
	// Sabriel Nix
    [
		'id' => 'sabrielnix',
		'type' => 'human',
		'first_name' => 'Sabriel',
		'last_name' => 'Nix',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => 191,
		'weight' => 85,
		'dead' => '0',
		'birth_date' => '06/06/1996',
		'birth_place' => 'Rio Rancho, Nouveau-Mexique, Etats-Unis',
		'hair' => "Noirs",
		'eyes' => "Marrons",
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],
	
	// Stephane Laroche
    [
		'id' => 'stephanelaroche',
		'type' => 'human',
		'first_name' => 'Stephane',
		'last_name' => 'Laroche',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => NULL,
		'birth_place' => 'France',
		'hair' => "Chauve",
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais, Français',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],
	
	// Gabriel Knight Ritter Belmont
    [
		'id' => 'gabrielknight',
		'type' => 'human',
		'first_name' => 'Gabriel',
		'last_name' => 'Knight Ritter Belmont',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => NULL,
		'birth_place' => 'Allemagne',
		'hair' => "Chauve",
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais, Allemand',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],
	
	// Cornelia Merrywick
    [
		'id' => 'corneliamerrywick',
		'type' => 'human',
		'first_name' => 'Cornelia',
		'last_name' => 'Merrywick',
		'aliases' => NULL,
		'sex' => 'female',
		'height' => 172,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '05/03/1991',
		'birth_place' => 'Rock Springs, Wyoming, Etats-Unis',
		'hair' => "Blonds",
		'eyes' => "Bleus",
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],
	
	// Sebastian Montgomery
    [
		'id' => 'sebastianmontgomery',
		'type' => 'human',
		'first_name' => 'Sebastian',
		'last_name' => 'Montgomery',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => NULL,
		'birth_place' => 'Etats-Unis',
		'hair' => "Bruns",
		'eyes' => NULL,
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],
	
	// Steeven Nelson
    [
		'id' => 'steevennelson',
		'type' => 'human',
		'first_name' => 'Steeven',
		'last_name' => 'Nelson',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => 172,
		'weight' => 60,
		'dead' => '0',
		'birth_date' => '01/01/1991',
		'birth_place' => 'Etats-Unis',
		'hair' => "Bruns",
		'eyes' => "Noisettes",
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],
	
	// Luis Serrano
    [
		'id' => 'luisserrano',
		'type' => 'human',
		'first_name' => 'Luis',
		'last_name' => 'Serrano',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '01/01/85',
		'birth_place' => 'Etats-Unis',
		'hair' => "Bruns",
		'eyes' => "Marrons",
		'ethnic_group' => 'hispanic',
		'status' => 'agent',
		'languages' => 'Anglais, Espagnol',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],
	
	// Travis Johnson
    [
		'id' => 'travisjohnson',
		'type' => 'human',
		'first_name' => 'Travis',
		'last_name' => 'Johnson',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => NULL,
		'birth_place' => 'Arizona, Etats-Unis',
		'hair' => "Chatains",
		'eyes' => "Marrons",
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],
	
	// Miles Sutherland
    [
		'id' => 'milessutherland',
		'type' => 'human',
		'first_name' => 'Miles',
		'last_name' => 'Sutherland',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => 188,
		'weight' => 86,
		'dead' => '0',
		'birth_date' => NULL,
		'birth_place' => 'Mokena, Illinois, Etats-Unis',
		'hair' => "Bruns",
		'eyes' => "Marrons",
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],
	
	// Sullivan Tessier
    [
		'id' => 'sullivantessier',
		'type' => 'human',
		'first_name' => 'Sullivan',
		'last_name' => 'Tessier',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => 177,
		'weight' => 83,
		'dead' => '0',
		'birth_date' => NULL,
		'birth_place' => 'Houma, Louisiane, Etats-Unis',
		'hair' => "Bruns",
		'eyes' => "Marrons",
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais, Français',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],
	
	// Rhea Streisand
    [
		'id' => 'rheastreisand',
		'type' => 'human',
		'first_name' => 'Rhea',
		'last_name' => 'Streisand',
		'aliases' => NULL,
		'sex' => 'female',
		'height' => 181,
		'weight' => 57,
		'dead' => '0',
		'birth_date' => NULL,
		'birth_place' => 'Romeo, Michigan, Etats-Unis',
		'hair' => "Blonds",
		'eyes' => "Bleus",
		'ethnic_group' => 'white',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Benito Quevedo
    [
		'id' => 'benitoquevedo',
		'type' => 'human',
		'first_name' => 'Benito',
		'last_name' => 'Quevedo',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => 188,
		'weight' => 80,
		'dead' => '0',
		'birth_date' => "13/08/1968",
		'birth_place' => 'San Simon, Arizona, Etats-Unis',
		'hair' => "Noirs",
		'eyes' => "Verts",
		'ethnic_group' => 'hispanic',
		'status' => 'agent',
		'languages' => 'Anglais, Espagnol',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Jerry Donovan
    [
		'id' => 'jerrydonovan',
		'type' => 'human',
		'first_name' => 'Jerry',
		'last_name' => 'Donovan',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => 176,
		'weight' => 74,
		'dead' => '0',
		'birth_date' => "27/05/1982",
		'birth_place' => 'Gardnerville, Nevada, Etats-Unis',
		'hair' => "Noirs",
		'eyes' => "Marrons",
		'ethnic_group' => 'hispanic',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Julius Casillas
    [
		'id' => 'juliuscasillas',
		'type' => 'human',
		'first_name' => 'Julius',
		'last_name' => 'Casillas',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => 187,
		'weight' => 73,
		'dead' => '0',
		'birth_date' => "03/09/1994",
		'birth_place' => 'Las Vegas, Nevada, Etats-Unis',
		'hair' => "Noirs",
		'eyes' => "Marrons",
		'ethnic_group' => 'black',
		'status' => 'agent',
		'languages' => 'Anglais',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Gabrielle Beauvais
    [
		'id' => 'gabriellebeauvais',
		'type' => 'human',
		'first_name' => 'Gabrielle',
		'last_name' => 'Beauvais',
		'aliases' => NULL,
		'sex' => 'female',
		'height' => 165,
		'weight' => 78,
		'dead' => '0',
		'birth_date' => "25/04/1967",
		'birth_place' => 'Livingston, New Jersey, Etats-Unis',
		'hair' => "Noirs",
		'eyes' => "Noirs",
		'ethnic_group' => 'black',
		'status' => 'agent',
		'languages' => 'Anglais, Français',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Gregory Terrell
    [
		'id' => 'gregoryterrell',
		'type' => 'human',
		'first_name' => 'Gregory',
		'last_name' => 'Terrell',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => 183,
		'weight' => 78,
		'dead' => '0',
		'birth_date' => "12/11/1989",
		'birth_place' => 'Saint-Louis, Missouri, Etats-Unis',
		'hair' => "Noirs",
		'eyes' => "Marrons",
		'ethnic_group' => 'black',
		'status' => 'agent',
		'languages' => 'Anglais, Français',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Vera F. Ramirez
    [
		'id' => 'veraframirez',
		'type' => 'human',
		'first_name' => 'Vera',
		'last_name' => 'F. Ramirez',
		'aliases' => NULL,
		'sex' => 'female',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '15/06/1968',
		'birth_place' => 'Tucson Estates, Arizona, Etats-Unis',
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'hispanic',
		'status' => 'agent',
		'languages' => 'Anglais, Espagnole',
		'place_id' => 'office_phoenix_az',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

];

$vampires = [
	// Abby Cordwell
    [
		'id' => 'abbycordwell',
		'type' => 'vampire',
		'first_name' => 'Abbigail',
		'last_name' => 'Cordwell',
		'aliases' => 'Abbigail Cordwell, Abby',
		'sex' => 'female',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '13/06/1996',
		'birth_place' => NULL,
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'unknown',
		'status' => 'civilian',
		'languages' => 'Anglais',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => 'clan_lasvegas',
		'sire_id' => 'vernonlangley',
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Birdie Tate
    [
		'id' => 'birdietate',
		'type' => 'vampire',
		'first_name' => 'Birdie',
		'last_name' => 'Tate',
		'aliases' => NULL,
		'sex' => 'female',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '26/03/1940',
		'birth_place' => NULL,
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'unknown',
		'status' => 'civilian',
		'languages' => 'Anglais',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => 'clan_lasvegas',
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Caleb Magnar (mort)
    [
		'id' => 'calebmagnar',
		'type' => 'vampire',
		'first_name' => 'Caleb',
		'last_name' => 'Magnar',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '1',
		'birth_date' => '08/05/1760',
		'birth_place' => NULL,
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'unknown',
		'status' => 'civilian',
		'languages' => 'Anglais',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => 'clan_lasvegas',
		'sire_id' => 'vernonlangley',
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Calvin Beck
    [
		'id' => 'calvinbeck',
		'type' => 'vampire',
		'first_name' => 'Calvin',
		'last_name' => 'Beck',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '10/11/1918',
		'birth_place' => NULL,
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'unknown',
		'status' => 'civilian',
		'languages' => 'Anglais',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => 'clan_lasvegas',
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Celosia (morte)
    [
		'id' => 'celosia',
		'type' => 'vampire',
		'first_name' => 'Celosia',
		'last_name' => '',
		'aliases' => NULL,
		'sex' => 'female',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '1',
		'birth_date' => '17/09/1895',
		'birth_place' => NULL,
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'unknown',
		'status' => 'civilian',
		'languages' => 'Anglais',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => 'clan_lasvegas',
		'sire_id' => 'calebmagnar',
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Charles Gates
    [
		'id' => 'charlesgates',
		'type' => 'vampire',
		'first_name' => 'Charles',
		'last_name' => 'Gates',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '19/09/1975',
		'birth_place' => NULL,
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'unknown',
		'status' => 'prisoner',
		'languages' => 'Anglais',
		'place_id' => 'prison_moreypeak_nv',
		'group_id' => 'clan_lasvegas',
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Leonardo Pezziali
    [
		'id' => 'leonardopezziali',
		'type' => 'vampire',
		'first_name' => 'Leonardo',
		'last_name' => 'Pezziali',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '14/08/1755',
		'birth_place' => NULL,
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'unknown',
		'status' => 'civilian',
		'languages' => 'Anglais',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => 'clan_lasvegas',
		'sire_id' => NULL,
		'self_control' => '1',
		'demon_id' => NULL,
	],

	// Margaret Lowery
    [
		'id' => 'margaretlowery',
		'type' => 'vampire',
		'first_name' => 'Margaret',
		'last_name' => 'Lowery',
		'aliases' => NULL,
		'sex' => 'female',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '12/12/1756',
		'birth_place' => NULL,
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'unknown',
		'status' => 'civilian',
		'languages' => 'Anglais, Français, Créole haïtien, Italien',
		'place_id' => 'office_nouvelleorleans_la',
		'group_id' => 'clan_nouvelleorleans_la',
		'sire_id' => NULL,
		'self_control' => '1',
		'demon_id' => NULL,
	],

	// Martin Clayton
    [
		'id' => 'martinclayton',
		'type' => 'vampire',
		'first_name' => 'Martin',
		'last_name' => 'Clayton',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '12/01/1941',
		'birth_place' => NULL,
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'unknown',
		'status' => 'civilian',
		'languages' => 'Anglais',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => 'clan_lasvegas',
		'sire_id' => 'estellastout',
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Maud Griffith
    [
		'id' => 'maudgriffith',
		'type' => 'vampire',
		'first_name' => 'Maud',
		'last_name' => 'Griffith',
		'aliases' => NULL,
		'sex' => 'female',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '15/12/1960',
		'birth_place' => NULL,
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'unknown',
		'status' => 'civilian',
		'languages' => 'Anglais',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => 'clan_lasvegas',
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Vernon Langlay (mort)
    [
		'id' => 'vernonlangley',
		'type' => 'vampire',
		'first_name' => 'Vernon',
		'last_name' => 'Langley',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '1',
		'birth_date' => '14/02/1667',
		'birth_place' => NULL,
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'unknown',
		'status' => 'civilian',
		'languages' => 'Anglais, Français',
		'place_id' => 'office_losangeles_ca',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Wiliam Adan
    [
		'id' => 'williamadan',
		'type' => 'vampire',
		'first_name' => 'William',
		'last_name' => 'Adan',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '05/02/1799',
		'birth_place' => NULL,
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'unknown',
		'status' => 'civilian',
		'languages' => 'Anglais, Russe, Français, Espagnol, Algonquin',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => 'clan_lasvegas',
		'sire_id' => NULL,
		'self_control' => '1',
		'demon_id' => NULL,
	],

	// Estella Stout
    [
		'id' => 'estellastout',
		'type' => 'vampire',
		'first_name' => 'Estella',
		'last_name' => 'Stout',
		'aliases' => NULL,
		'sex' => 'female',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '13/11/1941',
		'birth_place' => NULL,
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'unknown',
		'status' => 'civilian',
		'languages' => 'Anglais',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => 'clan_lasvegas',
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],
];

$warlocks = [
	// Aden McGuire
    [
		'id' => 'adenmcguire',
		'type' => 'warlock',
		'first_name' => 'Aden',
		'last_name' => 'McGuire',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '12/04/1753',
		'birth_place' => NULL,
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'unknown',
		'status' => 'civilian',
		'languages' => 'Anglais',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => 'circle_lasvegas',
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Corey Hunt
    [
		'id' => 'coreyhunt',
		'type' => 'warlock',
		'first_name' => 'Corey',
		'last_name' => 'Hunt',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '11/09/1813',
		'birth_place' => NULL,
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'unknown',
		'status' => 'civilian',
		'languages' => 'Anglais',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => 'circle_lasvegas',
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Dagan Devante
    [
		'id' => 'dagandevante',
		'type' => 'warlock',
		'first_name' => 'Dagan',
		'last_name' => 'Devante',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '01/01/1261',
		'birth_place' => NULL,
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'unknown',
		'status' => 'civilian',
		'languages' => 'Anglais',
		'place_id' => 'office_phoenix_az',
		'group_id' => 'circle_phoenix',
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Kharak Roshan
    [
		'id' => 'kharakroshan',
		'type' => 'warlock',
		'first_name' => 'Kharak',
		'last_name' => 'Roshan',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '01/01/-1500',
		'birth_place' => NULL,
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'unknown',
		'status' => 'civilian',
		'languages' => 'Anglais',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => 'circle_lasvegas',
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// River Lee
    [
		'id' => 'riverlee',
		'type' => 'warlock',
		'first_name' => 'River',
		'last_name' => 'Lee',
		'aliases' => NULL,
		'sex' => 'female',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '15/12/1435',
		'birth_place' => NULL,
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'unknown',
		'status' => 'civilian',
		'languages' => 'Anglais',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => 'circle_lasvegas',
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Sharon Kennedy (prison)
    [
		'id' => 'sharonkennedy',
		'type' => 'warlock',
		'first_name' => 'Sharon',
		'last_name' => 'Kennedy',
		'aliases' => NULL,
		'sex' => 'female',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '05/10/1930',
		'birth_place' => NULL,
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'unknown',
		'status' => 'prisoner',
		'languages' => 'Anglais',
		'place_id' => 'prison_moreypeak_nv',
		'group_id' => 'circle_lasvegas',
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],
];

$werewolves = [
	// Allie Hooper
    [
		'id' => 'alliehooper',
		'type' => 'werewolf',
		'first_name' => 'Allie',
		'last_name' => 'Hooper',
		'aliases' => NULL,
		'sex' => 'female',
		'height' => 143,
		'weight' => 42,
		'dead' => '0',
		'birth_date' => '10/02/2006',
		'birth_place' => "Las Vegas, Nevada, Etats-Unis",
		'hair' => "Roux",
		'eyes' => "Noisettes",
		'ethnic_group' => 'white',
		'status' => 'civilian',
		'languages' => 'Anglais',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => 'pack_griffesdevegas',
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Anthony Hooper
    [
		'id' => 'anthonyhooper',
		'type' => 'werewolf',
		'first_name' => 'Anthony',
		'last_name' => 'Hooper',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => 175,
		'weight' => 78,
		'dead' => '0',
		'birth_date' => '21/04/1976',
		'birth_place' => "Sacramento, Californie, Las Vegas",
		'hair' => "Bruns",
		'eyes' => "Marrons",
		'ethnic_group' => 'white',
		'status' => 'civilian',
		'languages' => 'Anglais',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => 'pack_griffesdevegas',
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Bess Odell
    [
		'id' => 'bessodell',
		'type' => 'werewolf',
		'first_name' => 'Bess',
		'last_name' => 'Odell',
		'aliases' => NULL,
		'sex' => 'female',
		'height' => 160,
		'weight' => 53,
		'dead' => '0',
		'birth_date' => '25/05/1981',
		'birth_place' => "Missoula, Montana, Etats-Unis",
		'hair' => "Chatains",
		'eyes' => "Marrons",
		'ethnic_group' => 'white',
		'status' => 'civilian',
		'languages' => 'Anglais',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => 'pack_griffesdevegas',
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Declan Samson (prison)
    [
		'id' => 'declansamson',
		'type' => 'werewolf',
		'first_name' => 'Declan',
		'last_name' => 'Samson',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => 206,
		'weight' => 146,
		'dead' => '0',
		'birth_date' => '03/02/1977',
		'birth_place' => "Nouvelle-Orléans, Louisiane, Etats-Unis",
		'hair' => "Bruns",
		'eyes' => "Gris",
		'ethnic_group' => 'white',
		'status' => 'prisoner',
		'languages' => 'Anglais, Français',
		'place_id' => 'prison_homochitto_ms',
		'group_id' => 'pack_nouvelleorleans_la',
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Garrett Stafford (prison)
    [
		'id' => 'garrettstafford',
		'type' => 'werewolf',
		'first_name' => 'Garrett',
		'last_name' => 'Stafford',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => 186,
		'weight' => 72,
		'dead' => '0',
		'birth_date' => '15/12/1980',
		'birth_place' => "Derby, Kansas, Etats-Unis",
		'hair' => "Roux",
		'eyes' => "Marrons",
		'ethnic_group' => 'white',
		'status' => 'prisoner',
		'languages' => 'Anglais',
		'place_id' => 'prison_moreypeak_nv',
		'group_id' => 'pack_fullmoonriders',
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Jackson Cox
    [
		'id' => 'jacksoncox',
		'type' => 'werewolf',
		'first_name' => 'Jackson',
		'last_name' => 'Cox',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => 175,
		'weight' => 75,
		'dead' => '0',
		'birth_date' => '03/02/1977',
		'birth_place' => "Portsmouth, Angleterre",
		'hair' => "Bruns",
		'eyes' => "Verts",
		'ethnic_group' => 'white',
		'status' => 'civilian',
		'languages' => 'Anglais',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => 'pack_griffesdevegas',
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Jordan Yeriva (prison)
    [
		'id' => 'jordanyeriva',
		'type' => 'werewolf',
		'first_name' => 'Jordan',
		'last_name' => 'Yeriva',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => 192,
		'weight' => 84,
		'dead' => '0',
		'birth_date' => '15/12/1987',
		'birth_place' => "Plovdiv, Bulgarie",
		'hair' => "Bruns",
		'eyes' => "Marrons",
		'ethnic_group' => 'white',
		'status' => 'prisoner',
		'languages' => 'Anglais, Bulgare',
		'place_id' => 'prison_moreypeak_nv',
		'group_id' => 'pack_fullmoonriders',
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Kendrick Tendor
    [
		'id' => 'kendricktendor',
		'type' => 'werewolf',
		'first_name' => 'Kendrick',
		'last_name' => 'Tendor',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => 179,
		'weight' => 92,
		'dead' => '0',
		'birth_date' => '28/07/1953',
		'birth_place' => "Las Vegas, Nevada, Etats-Unis",
		'hair' => "Gris",
		'eyes' => "Bleus",
		'ethnic_group' => 'white',
		'status' => 'civilian',
		'languages' => 'Anglais',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => 'pack_griffesdevegas',
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Lucille Dotson
    [
		'id' => 'lucilledotson',
		'type' => 'werewolf',
		'first_name' => 'Lucille',
		'last_name' => 'Dotson',
		'aliases' => NULL,
		'sex' => 'female',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '02/08/1965',
		'birth_place' => NULL,
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'unknown',
		'status' => 'civilian',
		'languages' => 'Anglais',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => 'pack_griffesdevegas',
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Nora Gibbons
    [
		'id' => 'noragibbons',
		'type' => 'werewolf',
		'first_name' => 'Nora',
		'last_name' => 'Gibbons',
		'aliases' => NULL,
		'sex' => 'female',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '13/09/1961',
		'birth_place' => NULL,
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'unknown',
		'status' => 'civilian',
		'languages' => 'Anglais',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => 'pack_griffesdevegas',
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Ozzy Wade
    [
		'id' => 'ozzywade',
		'type' => 'werewolf',
		'first_name' => 'Ozzy',
		'last_name' => 'Wade',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => 188,
		'weight' => 85,
		'dead' => '0',
		'birth_date' => '21/03/1962',
		'birth_place' => "Baker, Nevada, Etats-Unis",
		'hair' => "Chatains",
		'eyes' => "Bleus clairs",
		'ethnic_group' => 'white',
		'status' => 'civilian',
		'languages' => 'Anglais, Féérique, Démoniaque',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => 'pack_griffesdevegas',
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Roy Turner (prison)
    [
		'id' => 'royturner',
		'type' => 'werewolf',
		'first_name' => 'Roy',
		'last_name' => 'Turner',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '13/06/1986',
		'birth_place' => NULL,
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'unknown',
		'status' => 'prisoner',
		'languages' => 'Anglais, Serbe',
		'place_id' => 'prison_moreypeak_nv',
		'group_id' => 'pack_fullmoonriders',
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Victor Mooney
    [
		'id' => 'victormooney',
		'type' => 'werewolf',
		'first_name' => 'Victor',
		'last_name' => 'Mooney',
		'aliases' => NULL,
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '10/11/1968',
		'birth_place' => NULL,
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'unknown',
		'status' => 'civilian',
		'languages' => 'Anglais',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => 'pack_griffesdevegas',
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Zoe Chapman (prison)
    [
		'id' => 'zoechapman',
		'type' => 'werewolf',
		'first_name' => 'Zoe',
		'last_name' => 'Chapman',
		'aliases' => NULL,
		'sex' => 'female',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '30/06/1983',
		'birth_place' => NULL,
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'unknown',
		'status' => 'prisoner',
		'languages' => 'Anglais',
		'place_id' => 'prison_moreypeak_nv',
		'group_id' => 'pack_fullmoonriders',
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
    ],
];

$wanteds = [
	// Basriel Nix
    [
		'id' => 'basrielnix',
		'type' => 'human',
		'first_name' => 'Basriel',
		'last_name' => 'Nix',
		'aliases' => 'Basriel Nix',
		'sex' => 'male',
		'height' => '191',
		'weight' => '85',
		'dead' => '0',
		'birth_date' => '06/06/1996',
		'birth_place' => 'Nouveau-Mexique, Etats-Unis',
		'hair' => 'Noirs',
		'eyes' => 'Marron',
		'ethnic_group' => 'white',
		'status' => 'wanted',
		'languages' => 'Anglais, Démoniaque (supposé)',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// L'Homme Masque
    [
		'id' => 'hommemasque',
		'type' => 'unknown',
		'first_name' => 'L\'Homme Masqué',
		'last_name' => '',
		'aliases' => 'L\'Homme Masqué',
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => NULL,
		'birth_place' => NULL,
		'hair' => NULL,
		'eyes' => NULL,
		'ethnic_group' => 'unknown',
		'status' => 'wanted',
		'languages' => 'Anglais',
		'place_id' => 'office_newyork_ny',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Leslie Lohflower
    [
		'id' => 'leslielohflower',
		'type' => 'werewolf',
		'first_name' => 'Leslie',
		'last_name' => 'Lohflower',
		'aliases' => 'Leslie Lohflower',
		'sex' => 'male',
		'height' => '188',
		'weight' => '88',
		'dead' => '0',
		'birth_date' => '16/09/1995',
		'birth_place' => 'Santa Barbara, Californie, Etats-Unis',
		'hair' => 'Blond',
		'eyes' => 'Bleus',
		'ethnic_group' => 'white',
		'status' => 'wanted',
		'languages' => 'Anglais',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => 'pack_fullmoonriders',
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Micah Fuchs
    [
		'id' => 'micahfuchs',
		'type' => 'werewolf',
		'first_name' => 'Micah',
		'last_name' => 'Fuchs',
		'aliases' => 'Micah Fuchs',
		'sex' => 'male',
		'height' => '188',
		'weight' => '88',
		'dead' => '0',
		'birth_date' => '22/03/1996',
		'birth_place' => 'Cedar City, Utah, Etats-Unis',
		'hair' => 'Blond',
		'eyes' => 'Bleus',
		'ethnic_group' => 'white',
		'status' => 'wanted',
		'languages' => 'Anglais',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => 'pack_fullmoonriders',
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Otto
    [
		'id' => 'otto',
		'type' => 'warlock',
		'first_name' => 'Otto',
		'last_name' => '',
		'aliases' => 'Otto',
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => NULL,
		'birth_place' => NULL,
		'hair' => 'Blond',
		'eyes' => 'Vert',
		'ethnic_group' => 'white',
		'status' => 'wanted',
		'languages' => 'Anglais',
		'place_id' => 'office_newyork_ny',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],

	// Curtis Levesque
	[
		'id' => 'curtislevesque',
		'type' => 'werewolf',
		'first_name' => 'Curtis',
		'last_name' => 'Levesque',
		'aliases' => 'Curtis Levesque',
		'sex' => 'male',
		'height' => NULL,
		'weight' => NULL,
		'dead' => '0',
		'birth_date' => '17/09/1936',
		'birth_place' => 'Temple, Géorgie, Etats-Unis',
		'hair' => 'Gris',
		'eyes' => 'Marrons',
		'ethnic_group' => 'white',
		'status' => 'wanted',
		'languages' => 'Anglais',
		'place_id' => 'office_philadelphie_pa',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL
	],

	// Aldo Caballero
	[
		'id' => 'aldocaballero',
		'type' => 'warlock',
		'first_name' => 'Aldo',
		'last_name' => 'Caballero',
		'aliases' => 'Aldo Caballero, Smoke, SM0-ke',
		'sex' => 'male',
		'height' => '174',
		'weight' => '75',
		'dead' => '0',
		'birth_date' => '21/02/1591',
		'birth_place' => 'Quilmes, Argantina',
		'hair' => 'Chatains',
		'eyes' => 'Gris',
		'ethnic_group' => 'hispanic',
		'status' => 'wanted',
		'languages' => 'Anglais, Espagnol',
		'place_id' => 'office_watertown_ny',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL
	],

	// Lazare Thornton
	[
		'id' => 'lazarethornton',
		'type' => 'vampire',
		'first_name' => 'Lazare',
		'last_name' => 'Thornton',
		'aliases' => 'Lazare Thornton, Monsieur L., Le Roi de l\'Escapade, escape_king',
		'sex' => 'male',
		'height' => '173',
		'weight' => '71',
		'dead' => '0',
		'birth_date' => '23/07/1837',
		'birth_place' => 'Cortland, Ohio, Etats-Unis',
		'hair' => 'Noirs',
		'eyes' => 'Marrons',
		'ethnic_group' => 'white',
		'status' => 'wanted',
		'languages' => 'Anglais',
		'place_id' => 'office_jackson_ms',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '1',
		'demon_id' => NULL
	],
  
	// Steven Maher
	[
		'id' => 'stevenmaher',
		'type' => 'warlock',
		'first_name' => 'Steven',
		'last_name' => 'Maher',
		'aliases' => 'Steven Mahers',
		'sex' => 'male',
		'height' => '172',
		'weight' => '78',
		'dead' => '0',
		'birth_date' => '14/05/1712',
		'birth_place' => 'Crestwood, Kentucky, Etats-Unis',
		'hair' => 'Chatains',
		'eyes' => 'Marrons',
		'ethnic_group' => 'white',
		'status' => 'wanted',
		'languages' => 'Anglais',
		'place_id' => 'office_desmoines_ia',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL
	],

	// Herschel Mayer, Le Dissocieur
	[
		'id' => 'herschelmayer',
		'type' => 'human',
		'first_name' => 'Herschel',
		'last_name' => 'Mayer',
		'aliases' => 'Herschel Mayer, Le Dissocieur, Le Déplaceur',
		'sex' => 'male',
		'height' => '183',
		'weight' => '78',
		'dead' => '0',
		'birth_date' => '29/05/1977',
		'birth_place' => 'Glendale Heights village, Illinois, Etats-Unis',
		'hair' => 'Chatains',
		'eyes' => 'Bleus',
		'ethnic_group' => 'white',
		'status' => 'wanted',
		'languages' => 'Anglais, Espagnol',
		'place_id' => 'office_washington_dc',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL
	],

	// Never Espinoza
	[
		'id' => 'neverespinoza',
		'type' => 'human',
		'first_name' => 'Never',
		'last_name' => 'Espinoza',
		'aliases' => 'Never Espinoza',
		'sex' => 'male',
		'height' => '178',
		'weight' => '73',
		'dead' => '0',
		'birth_date' => '04/08/1994',
		'birth_place' => 'Villavicencio, Colombie',
		'hair' => 'Noirs',
		'eyes' => 'Marrons',
		'ethnic_group' => 'hispanic',
		'status' => 'wanted',
		'languages' => 'Anglais, Espagnol',
		'place_id' => 'office_littlerock_ar',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL
	],

	// Estell Pagano
	[
		'id' => 'estellpagano',
		'type' => 'human',
		'first_name' => 'Estell',
		'last_name' => 'Pagano',
		'aliases' => 'Estell Pagano',
		'sex' => 'female',
		'height' => '171',
		'weight' => '75',
		'dead' => '0',
		'birth_date' => '19/10/1978',
		'birth_place' => 'Princeton, Virginie-Occidentale, Etats-Unis',
		'hair' => 'Noirs',
		'eyes' => 'Marrons',
		'ethnic_group' => 'black',
		'status' => 'wanted',
		'languages' => 'Anglais',
		'place_id' => 'office_dallas_tx',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL
	],
  
	// Melony Weatherford
	[
		'id' => 'melonyweatherford',
		'type' => 'werewolf',
		'first_name' => 'Melony',
		'last_name' => 'Weatherford',
		'aliases' => 'Melony Weatherford',
		'sex' => 'female',
		'height' => '167',
		'weight' => '58',
		'dead' => '0',
		'birth_date' => '05/02/1962',
		'birth_place' => 'San Diego, Californie, Etats-Unis',
		'hair' => 'Blancs',
		'eyes' => 'Bleus',
		'ethnic_group' => 'white',
		'status' => 'wanted',
		'languages' => 'Anglais',
		'place_id' => 'office_dallas_tx',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL
	],

	// Velvet Janssen
	[
		'id' => 'velvetjanssen',
		'type' => 'warlock',
		'first_name' => 'Velvet',
		'last_name' => 'Janssen',
		'aliases' => 'Velvet Janssen',
		'sex' => 'female',
		'height' => '168',
		'weight' => '58',
		'dead' => '0',
		'birth_date' => '30/04/1768',
		'birth_place' => 'Gävle, Suède',
		'hair' => 'Chatains',
		'eyes' => 'Noisettes',
		'ethnic_group' => 'white',
		'status' => 'wanted',
		'languages' => 'Anglais',
		'place_id' => 'office_dallas_tx',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL
	],

  
];

$prisoners = [
	// Clayton Moore, Le Doc
    [
		'id' => 'claytonmoore',
		'type' => 'human',
		'first_name' => 'Clayton',
		'last_name' => 'Moore',
		'aliases' => 'Clayton Moore, Le Doc, Docteur',
		'sex' => 'male',
		'height' => '182',
		'weight' => '81',
		'dead' => '0',
		'birth_date' => '30/05/1970',
		'birth_place' => 'Athens, Georgie, Etats-Unis',
		'hair' => 'Chatain',
		'eyes' => 'Bleus',
		'ethnic_group' => 'white',
		'status' => 'prisoner',
		'languages' => 'Anglais, Allemand, Espagnol',
		'place_id' => 'office_lasvegas_nv',
		'group_id' => NULL,
		'sire_id' => NULL,
		'self_control' => '0',
		'demon_id' => NULL,
	],
];

$demons = [
	// L'Illusionniste
    [
		'id' => 'phantasme',
		'type' => 'demon',
		'first_name' => 'Phantasme',
		'last_name' => '',
		'aliases' => 'Phantasme, Éphémeros, L\'Illusionniste, Le Forgeur de Liens, Aetheron, Révéro, Deceptra, Le Semeur, Le Tisserand des Pactes',
		'sex' => NULL,
		'height' => '200',
		'weight' => NULL,
		'status' => 'wanted',
		'dead' => '0',
		'birth_date' => NULL,
		'birth_place' => NULL
	],
];