name: Fly Deploy
run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}

on:
  push:
    branches:
      - master

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  create-cache:
    name: Create cache
    runs-on: ubuntu-latest
    steps:
      - run: ls /home/runner/work/WeMAD/WeMAD/storage/
#  composer-update:
#    name: Update composer
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: superfly/flyctl-actions/setup-flyctl@master
#      - run: composer update
  
#  cache-clear:
#    name: Clear cache
#    runs-on: ubuntu-latest
#    needs: composer-update
#    steps:
#      - uses: actions/checkout@v3
#      - uses: superfly/flyctl-actions/setup-flyctl@master
#      - run: php artisan cache:clear
  
#  deploy:
#    name: Deploy app
#    runs-on: ubuntu-latest
#    needs: [composer-update, cache-clear]
#    steps:
#      - uses: actions/checkout@v3
#      - uses: superfly/flyctl-actions/setup-flyctl@master
#      - run: flyctl deploy --remote-only
