name: Fly Deploy
run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}

on:
  push:
    branches:
      - master

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  start-machine:
    name: Start machine
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl machine start 148ed431f39658
  create-cache:
    name: Create cache
    runs-on: ubuntu-latest
    needs: start-machine
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl ssh console -C "storage/framework/cache/"

#  composer-update:
#    name: Update composer
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: superfly/flyctl-actions/setup-flyctl@master
#      - run: composer update
  
#  cache-clear:
#    name: Clear cache
#    runs-on: ubuntu-latest
#    needs: composer-update
#    steps:
#      - uses: actions/checkout@v3
#      - uses: superfly/flyctl-actions/setup-flyctl@master
#      - run: php artisan cache:clear
  
#  deploy:
#    name: Deploy app
#    runs-on: ubuntu-latest
#    needs: [composer-update, cache-clear]
#    steps:
#      - uses: actions/checkout@v3
#      - uses: superfly/flyctl-actions/setup-flyctl@master
#      - run: flyctl deploy --remote-only
