name: Fly Deploy
run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}

on:
  push:
    branches:
      - master

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl machine start 148ed431f39658; flyctl ssh console -C "mkdir storage/framework/cache/data"; flyctl ssh console -C "php artisan config:cache"; flyctl ssh console -C "php artisan cache:clear"; composer dump-autoload; composer install; flyctl deploy --remote-only