name: Fly Deploy
run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}

on:
  push:
    branches:
      - master

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: echo "\n--- Start machine ---\n"; flyctl machine start 148ed431f39658; echo "\n--- Create cache dir ---\n"; flyctl ssh console -C "mkdir -p storage/framework/cache/data"; echo "\n--- artisan cache:clear ---\n"; flyctl ssh console -C "php artisan cache:clear"; echo "\n--- artisan config:cache ---\n"; flyctl ssh console -C "php artisan config:cache"; echo "\n--- composer dump-autoload ---\n"; composer dump-autoload; echo "\n--- composer install ---\n"; composer install; echo "\n--- composer update ---\n"; composer update --no-scripts; echo "\n--- deploy ---\n"; flyctl deploy --remote-only